// This file is auto-generated by script/generateGlobalTypes.ts
// Do not edit manually.

export {};

declare global {
  var AddAnotationUI: any;
  var addExperienceVisited: (exp_id?: null) => void;
  var AddFloatingApp:
    | ((options: {
        App: Element;
        title: string;
        position: { x: number; y: number };
        size: { width: number; height: number };
      }) => unknown)
    | ((options: {
        App: Element;
        title: string;
        position: { x: number; y: number };
        size: { width: number; height: number };
        type: string;
      }) => unknown);
  var ADDING_TOPLAYLIST_TIMEOUT: null;
  var AddNowBarApp: (arg0: Element, id: string) => unknown;
  var AddToPlaylistData: null;
  var AlreadySet: boolean;
  var AnnotationIcon: any;
  var AnnotationsData: {};
  var AnnotationSortFunction: (a: any, b: any) => any;
  var AnnotationUISingleMode: boolean;
  var appendImageToEditorHTML: (fileObject: any) => string;
  var arrowActionsFreeze: boolean;
  var bible: any;
  var BOOKID_DATA: any;
  var ButtonStyle: any;
  var clickWait: boolean;
  var CLONE_DATA: (value: any, seen?: Map<any, any>) => any;
  var CloseVideoOverlay: () => unknown;
  var COLLECTION_SETTER: (newCollections: any) => void;
  var COLLECTIONS: { [x: number]: { collection: any[]; name: string } };
  var Components: Bot;
  var CONSTANTS: {
    YT_PREFIX: string;
    BOT_TYPE: { TESTAMENT: string; SECTION: string; BOOK: string };
  };
  var CountIgnoreSave: number;
  var createUUID: () => unknown;
  var creatingPlaylist: any;
  var CURRENNT_SOUND_ID: string | null;
  var CurrentIndexItem: {};
  var CurrentViewerID: null;
  var DEFAULT_UPLOAD_ICON: string;
  var defaultcurrentHistory: any;
  var defaultplaylistChecked: string;
  var defaultplaylistProgress: string;
  var demoInteractionWait: boolean;
  var DragDrop: any;
  var EDIT_COLLECTION_ID: null;
  var extractIdFromUrl: (url: string) => string | null | undefined;
  var FireEditContent: () => unknown;
  var FirstAnnnotationItem: string;
  var FloatBarStyle: {
    position: string;
    bottom: number;
    left: number;
    width: string;
    backgroundColor: string;
    padding: string;
  };
  var FocusOnVerse: any;
  var FORMAT_DATE:
    | ((date: string | Date, text: string, text2: string) => unknown)
    | ((date: string, text: string, text2: string) => unknown)
    | ((date: unknown, text: string, text2: string) => unknown);
  var FORMAT_YYYY_MM_DD: (arg0: Date) => unknown;
  var generateEmbedFromUrl:
    | ((arg0: string, arg1: string) => unknown)
    | ((arg0: string) => unknown);
  var GetColor:
    | ((i: number, length: number) => unknown)
    | ((i: number, length: unknown) => unknown)
    | ((i: number, limitOfLines: number) => unknown);
  var getExtensionFromMimeType: (mimeType: string) => any;
  var getFileIconByMimeType: (text: string) => unknown;
  var GetLabel: any;
  var GetVerseSummaryHeading: (
    verses: number[]
  ) => (string | number | undefined)[];
  var getVisitedExperince: () => any;
  var HandleOnButtonPress:
    | ((value: -1) => unknown)
    | ((value: number) => unknown);
  var HandleStop: () => unknown;
  var HandleStopPlayVideo: () => unknown;
  var HandleStopPlayVoice: () => unknown;
  var HandleUploadFiles: (files: any) => Promise<void>;
  var hasASharedPlaylist: boolean;
  var HISTORYExploreMode: boolean;
  var i18n: any;
  var i18next: any;
  var ImageWrapper: any;
  var isBlackFadeRegistered: boolean;
  var isCachedDataRef: any;
  var ISCommandBox: boolean;
  var isModalRegistered: boolean;
  var IsQueuePresent: boolean;
  var isRecording: boolean;
  var isScreenRecording: boolean;
  var IsVideoAttachment: (dataitem: any) => boolean;
  var LAST_CLICK_EMBED_ID: number;
  var LAST_CLICK_EMBED_PARENT: any;
  var LAST_CLICK_ID: number;
  var LAST_INDEX_CHECKLIST_CHECKED: number;
  var LAST_QUEUE_IIEM: {};
  var LastClickX: number;
  var LastClickY: number;
  var LASTKEY_COMMAND_BOX: any;
  var LasttAddedToPlaylist: any;
  var LatestPlaylistID: null;
  var LoadedPlaylistAnnotations: {};
  var LoadingOldPlaylist: boolean;
  var LocaleStorage: Bot;
  var MOBILE_VIEWPORT_THRESHOLD: number;
  var ModifyTransformedHistory: null;
  var NagiationTimeout: null | NodeJS.Timeout;
  var objectComparator:
    | ((data: unknown, lastData: unknown, items: string[]) => unknown)
    | ((dataItem: unknown, lastData: unknown, items: string[]) => unknown)
    | ((item: unknown, lastData: unknown, items: string[]) => unknown);
  var onCurrentCollectionEdit: null;
  var OpenRefTimeout: Timeout;
  var OpenVideoOverlay: () => unknown;
  var PLAY_TIMER: Timeout;
  var PLAYING_SOUND: {};
  var PlayingPlaylist: any;
  var PlayingPlaylistCheckedItems: {};
  var PlayingPlaylists: {};
  var PlayingPlaylistSetHeading: StateUpdater<string>;
  var PlaylingItemVisitiedMap: StateUpdater<any>;
  var Playlist: any;
  var PlaylistPlaytoggleHide: () => void;
  var PlaylistReferLinks: {};
  var playlists: any;
  var PlaylistsGroups: any;
  var PPchecklistEnabled: any;
  var PPclosestNearDateEvent: Record<string, boolean>;
  var PPcurrentItemID: any;
  var PPcurrentItemName: any;
  var PPcurrentPlaylistName: any;
  var PPfirstActiveIndex: number;
  var PPfirstIndex: number;
  var PPnextItemName: any;
  var PPpastDateEvents: Record<string, boolean>;
  var PPplaylist: any;
  var PPplaylistName: any;
  var PPprevItemName: any;
  var PPreadingPlanEnabled: any;
  var PPsubIndex: any;
  var PPthh: any;
  var PPtypeContent: any;
  var PREDEFINED_ICONS: string;
  var Previous_ID_Floading_App_PL: null;
  var PreviousHTML: null;
  var ProjectMenuState: {
    hideHeadings: boolean;
    areBooksClosed: boolean;
    projectSettings: {};
    showVersionHistory: boolean;
  };
  var pseudoIndentifier: string;
  var RawName: string;
  var READING_PLAN_WORK: boolean;
  var RECORD_SEPARATOR: string;
  var RecordingValue: any;
  var REMOTE_UPDATE_TIMER: null;
  var RemotePlaylistPlayed: boolean;
  var RemoveFloatingApp: (appId: any) => void;
  var RenderLinkTimer: Timeout;
  var RenderPlaylist: () => unknown;
  var RenderPlaylistPlaying: () => unknown;
  var RenderPlaylistTimer: null;
  var savePlaylistProgress:
    | (() => unknown)
    | ((id: string, progressID: string, parentID?: string) => void);
  var SelectedItemIDForAttachments: null;
  var SetActiveDate: (lastActiveDateID: number) => unknown;
  var SetAnnotationData: (items: never[]) => unknown;
  var SetAuthSwtich: (arg0: (p: boolean) => boolean) => unknown;
  var SetBookmarks: (options: {}) => unknown;
  var SetCheckedItemsPlayingPlaylist: (checkedItemsTemp: {}) => unknown;
  var SetCommandBoxFilter: (text: string) => unknown;
  var SetCurreIndexDirect: null;
  var SetCurreIndexPlaylist: (
    index: number,
    playListSubIndex: unknown
  ) => unknown;
  var SetCurrentItem: StateUpdater<{}>;
  var SetEditAnnoData: ((options: null) => unknown) | null;
  var SetEditAttachmentItem: StateUpdater<{
    id: null;
    parentID: null;
    selectedType: string;
    name: string;
    data: string;
    link: string;
    mediaType: string;
    text: null;
  }>;
  var SetEditData:
    | ((options: {
        color: null;
        id: null;
        name: null;
        description: null;
        icon: null;
      }) => unknown)
    | ((options: {
        color: string;
        id: string;
        name: string;
        description: string;
        icon: string;
      }) => unknown);
  var SetEditRichText: null;
  var setHide: any;
  var setHistoryLocale: (newHistory?: never[], id?: string) => void;
  var SetIncrementalCountPlayingPlaylist: null;
  var SetItemsPlayer: null;
  var SetMediaURL: (link: null) => unknown;
  var setOpenAttachLink: (flag: boolean) => unknown;
  var SetPlayingList: () => void;
  var SetPlayingPlaylists: null;
  var SetPlaylistGroups: StateUpdater<any>;
  var SetPlaylists: any;
  var setPriorities: () => void;
  var SetProjectMenuState: StateUpdater<{
    hideHeadings: boolean;
    areBooksClosed: boolean;
    projectSettings: {};
    showVersionHistory: boolean;
  }>;
  var SetRecording: null | StateUpdater<any>;
  var SetRecordingData: ((arg0: null) => unknown) | null;
  var SetRenamingPlaylist: (val: boolean) => unknown;
  var SetRenderMylist: StateUpdater<any>;
  var SetSelectedAnnotations: null;
  var SetShowAddToPlaylist: (flag: boolean) => unknown;
  var SetSplitAppPanel2:
    | ((arg0: Element) => unknown)
    | ((arg0: null) => unknown);
  var SetTab: ((text: string) => unknown) | null;
  var setTabPlaylist: (text: string) => unknown;
  var SetTextInfo: StateUpdater<string>;
  var Settings_Icon: string;
  var setVersesState: (versesState: number[]) => unknown;
  var SetVideoSrc: StateUpdater<boolean>;
  var shareProfileName: boolean;
  var shareProfilePic: any;
  var ShowCommandBox: () => unknown;
  var SmallPlaybackContent: () => unknown;
  var StopPlayingPlaylistModal: (flag: boolean) => unknown;
  var StopVideoRecording: boolean;
  var SYSTEM_PROMPT: string;
  var ThruCommandBox: boolean;
  var TIMER_SHOW_NEXT: Timeout;
  var TOAST_NOTIFICATION_TIMEOUT: Timeout;
  var ToggleCommandBox: () => unknown;
  var TogglePlaylistSuggestions: () => unknown;
  var TogglePreview: () => unknown;
  var ToggleVideoLayout: (flag: boolean) => unknown;
  var tt: any;
  var UPDATE_VIA_SHOUT: boolean;
  var updateCustomHeight: (value: number) => unknown;
  var UpdateJustAddedToQueue: (flag: boolean) => unknown;
  var uploadFilesReusable: (options: { files: File[] }) => unknown;
  var UsedTags: any[];
  var validateUrl: (url: string) => unknown;
  var ValidTypes: {
    verse: boolean;
    chapter: boolean;
    "verse-range": boolean;
    "chapter-range": boolean;
    "verse-grouped": boolean;
    "chapter-grouped": boolean;
  };
  var VideoRecordTab: any;
  var WAS_PREV_AUTH: boolean;
}
