// This file is auto-generated by script/generateGlobalTypes.ts
// Do not edit manually.

export {};

declare global {
  var AnnotationIcon: ({
    className,
  }: {
    className?: string | undefined;
  }) => Element;
  var getSectionBookRage: (sectionRank: number) => number[];
  var IMGS: { AOLABSRC: string };
  var IsHidden: boolean;
  var isUIOpen: boolean;
  var isValidGoogleSheetsUrl: (url: string) => boolean;
  var IsVideoUrl: (url: string) => boolean;
  var PendingAction: () => unknown;
  var playListDB: never[];
  var PlaylistIcon: ({
    className,
  }: {
    className?: string | undefined;
  }) => Element;
  var sanitizeObject: (obj: any) => any;
  var SELECTIONTYPE: { TESTAMENT: string; SECTION: string; BOOK: string };
  var SetHidePlaylist: StateUpdater<boolean>;
  var SetIsQueuePlaying: StateUpdater<boolean>;
  var SetPlayingPlaylist: null;
  var SetPlaylistForforcedHeight: (arg0: number) => unknown;
  var setPredefinedIcons: boolean;
  var SetSidebarOpen: StateUpdater<boolean>;
  var ToggleGreyCheckPLayingPlaylist: (arg0: null) => unknown;
  var validateImage: (arg0: string) => unknown;
}
