// This file is auto-generated by script/generateGlobalTypes.ts
// Do not edit manually.

export {};

declare global {
  var __emitLock: {};
  var __lastBookEmit: number;
  var __lastEmitData: {};
  var __lastEmitTime: {};
  var __lastHistorySchedule: number;
  var __navCooldownUntil: number;
  var __remoteBookUpdate: boolean;
  var _hold: boolean;
  var _holdTimeout: Timeout;
  var _skipNextMouse: boolean;
  var AccountSettingsEnteredFrom: string;
  var activeCanvasId: null;
  var ActiveTab: null;
  var ADD_TO_QUEUE_ITEM: any;
  var ADD_VERSE_ITEM_PLAYLIST_GROUP_ID: any;
  var AddApplication:
    | ((arg0: { id: string; App: Element; minWidth: string }) => unknown)
    | ((arg0: {
        id: string;
        App: Element;
        to: string;
        minWidth: string;
      }) => unknown)
    | ((arg0: {
        id: string;
        App: Element;
        to: string;
        minWidth: string;
        panelKey: string;
      }) => unknown);
  var AddFloatingApp: any;
  var AddNowBarApp: any;
  var AddTab:
    | ((arg0: {
        id: string;
        taken: boolean;
        data: {
          use: string;
          type: string;
          book: any;
          bookId: any;
          chapter: any;
          translation: string;
        };
      }) => any)
    | ((arg0: {
        id: string;
        taken: boolean;
        data: {
          use: string;
          type: string;
          book: any;
          bookId: string;
          chapter: number;
          translation: string;
        };
      }) => any)
    | ((arg0: {
        id: string;
        taken: boolean;
        data: {
          use: string;
          type: string;
          book: any;
          bookId: string;
          chapter: number;
          translation: string;
          shortName: string;
        };
      }) => any)
    | ((arg0: {
        id: string;
        taken: boolean;
        data: {
          use: string;
          type: string;
          book: string;
          bookId: any;
          chapter: number;
          translation: any;
          shortName: any;
        };
      }) => any)
    | ((arg0: any) => any);
  var AddTool: () => void;
  var AIDataChannel: null;
  var AISetStart: (arg0: boolean) => unknown;
  var AnimateTagObject: any;
  var animationBotsData: any;
  var annotInitialized: any;
  var API: Bot;
  var AppStartedSuccessfully: boolean;
  var aquiferApis: any;
  var ArrowDownConfig: any;
  var availableLanguages: (
    | { code: string; name: string; nativeName: string; rtl?: undefined }
    | { code: string; name: string; nativeName: string; rtl: boolean }
  )[];
  var BibleData: null;
  var BibleStackManager: Bot;
  var BibleVizUtils: {
    Classes: Bot;
    Data: Bot;
    Functions: Bot;
    Services: Bot;
    Main: Bot;
  };
  var BookId: any;
  var bookModalOpen: (arg0: boolean) => unknown;
  var botId: any;
  var C_E: never[];
  var CanvasMode: boolean;
  var changeLanguage: (lng: string) => Promise<void>;
  var changes: {};
  var ChangeTranslation:
    | ((arg0: string, arg1: unknown, arg2: string | undefined) => unknown)
    | ((arg0: string, arg1: unknown, arg2: string) => unknown)
    | ((arg0: string) => unknown)
    | ((arg0: unknown, arg1: unknown, arg2: string) => unknown);
  var CHAPTER_DATA: {
    use: string;
    first: boolean;
    type: string;
    book: string;
    bookId: string;
    chapter: number;
    translation: string;
    shortName: string;
  };
  var CHATBOT_PANEL_ID: string;
  var chatbotPresent: boolean;
  var CheckToolbarOverflow: () => unknown;
  var CLEARABLE_LERPING: boolean;
  var ClearAllWordHighlights: () => void;
  var ClearNowBarApps: () => void;
  var ClearUserSelection: () => unknown;
  var CloseModal: () => unknown;
  var CloseNewList: () => unknown;
  var closePopupSettings: () => unknown;
  var ColorLerper: Bot;
  var ContextMenuOptions: never[];
  var continousRotateBot: (arg0: Bot | Bot[], arg1: string) => unknown;
  var createEvent: null;
  var currentActiveItem: string;
  var CurrentActivePanel: null;
  var CurrentActiveTabData:
    | {
        use: string;
        first: boolean;
        type: string;
        book: string;
        bookId: string;
        chapter: number;
        translation: string;
        shortName: string;
      }
    | undefined;
  var CurrentBookData: {
    use?: string | undefined;
    first?: boolean | undefined;
    type?: string | undefined;
    book?: string | undefined;
    bookId?: string | undefined;
    chapter?: number | undefined;
    translation?: string | undefined;
    shortName?: string | undefined;
  };
  var CurrentColors: any;
  var currentCursor: null;
  var currentExperience: number;
  var currentLerps: null;
  var CurrentPanelAvailable: null;
  var currentReference: null;
  var currentReferenceKey: string;
  var CurrentTab: any;
  var DCRef: RTCDataChannel;
  var DEFAULT_TOOLBAR_PRIORITY: string[];
  var defaultPortalName: any;
  var EditorFns: {
    bold: () => void;
    italic: () => void;
    underline: () => void;
    strikethrough: () => void;
    superscript: () => boolean;
    subscript: () => boolean;
    alignLeft: () => boolean;
    alignCenter: () => boolean;
    alignRight: () => boolean;
    alignJustify: () => boolean;
    undo: () => boolean;
    redo: () => boolean;
    toggleBulletList: () => boolean;
    toggleOrderedList: () => boolean;
    onFontStyleChange: (style: any) => void;
    onParagraphChange: (value: any) => void;
    insertAttachment: (name: any, url: any) => void;
    insertLink: (url: any) => boolean;
    removeLink: () => boolean;
    insertImage: (url: any) => boolean;
    setLineHeight: (height: any) => void;
    clear: () => void;
    setTextColor: (color: any) => void;
    setHighlightColor: (color: any) => void;
    setFontFamily: (font: any) => void;
    setFontSize: (size: any) => void;
    getHtml: () => string;
    setHtml: (html: any) => boolean;
    exportJson: () => void;
    importJson: (json: any) => void;
    aiHighlight: (prompt: any) => Promise<void>;
  };
  var EditorTextMode: string;
  var EditorToolbar: {
    setPriorities(ids: any): void;
    getPriorities(): any;
    resetPriorities(): void;
  };
  var ENCRYPT_SALT_KEY: string;
  var EVENT_PANEL_ID: string;
  var eventApis: any;
  var eventBotConfig: any;
  var eventData: any;
  var eventDataLoading: boolean;
  var eventItemActive: boolean;
  var eventQuery: string;
  var eventTLActive: boolean;
  var eventToolApp: boolean;
  var eventUtils: {
    attachQueryToURL: (url: any, params: any) => string;
    getAllChildIds: (id: string, customMask?: string) => any;
    parentCheck: (childId: any, parentId: any) => any;
  };
  var focusOnVisibleButton: () => unknown;
  var FollowSpecificUser: (targetUserId: any) => Promise<void>;
  var GAME_MODES: any;
  var GetBooksDataForMenu: (arg0: string, arg1: unknown) => unknown;
  var GetOrSetVisualInTags:
    | ((arg0: string, arg1: null) => unknown)
    | ((arg0: string) => unknown);
  var GetUserSessionInfo: (arg0: string) => unknown;
  var GlobalChapter: number;
  var GUESSING_GAME_DIFFICULTY_LEVEL: number;
  var HandleSharedTabClick: () => unknown;
  var HandleStorageChange: (e: StorageEvent) => void;
  var hideSeekPlaying: any;
  var HIGHLIGHT_BG_COLOR: any;
  var HIGHLIGHT_TIMER: Timeout;
  var HighlightedSectionKey: any;
  var HighlightedVerseNumber: any;
  var HighlightStudyNoteSection: (arg0: any) => any;
  var HighlightVerse: (arg0: number, arg1: string) => unknown;
  var HighlightWords: (config: any) => void;
  var HistoryTimePeriodInfo: any;
  var html2canvas: (
    arg0: Element,
    arg1: { backgroundColor: null; useCORS: boolean }
  ) => unknown;
  var Init: () => unknown;
  var initAssistantSpeechMonitoring: () => void;
  var initialChildrens: never[];
  var InviteUser: (arg0: string) => unknown;
  var IS_PLAYLIST_ACTIVE: boolean;
  var isAbleToRightClick: boolean;
  var IsEditingAnnotation: boolean;
  var isLastItemCombine: boolean;
  var IsMobileNow: () => unknown;
  var IsPlaylistPlaying: boolean;
  var IsPrivateMode: () => unknown;
  var IsToolActive: (
    label: any,
    { inSet }?: { inSet?: string | undefined }
  ) => boolean;
  var IsToolInPageToolbar: (
    label: any,
    { inSet }?: { inSet?: string | undefined }
  ) => boolean;
  var IsToolSraterToolbar: (
    label: any,
    { inSet }?: { inSet?: string | undefined }
  ) => boolean;
  var KEY_HOLD: {};
  var LAST_CLICKED_BOOK_CHAPTER: {
    type: string;
    content: string;
    additionalInfo: {
      bookRank: any;
      bookName: string;
      chapter: number;
      data: { [key: string]: any };
    };
  };
  var LastClickedPanelUpdate: any;
  var LayoutBibleData: any;
  var LayoutBookData: any;
  var LayoutBookStructure: any;
  var LayoutChapterData: any;
  var LERP_YT_TIMEOUT: Timeout;
  var makingApp: null;
  var MakingNewTab: boolean;
  var makingPlaylist: boolean;
  var mapPanelHistoryUpdate: () => unknown;
  var MapsManager: Bot;
  var MeshState: { Hidden: string; Shown: string; Translucent: string };
  var moveEventBots: any;
  var NavFunctions: any;
  var ObjectPooler: Bot;
  var ON_VERSE_CLICK: any;
  var Open:
    | ((arg0: string, arg1: number, arg2: string) => unknown)
    | ((arg0: string, arg1: number) => unknown)
    | ((arg0: unknown, arg1: number, arg2: string, arg3: string) => unknown)
    | ((arg0: unknown, arg1: number, arg2: unknown) => unknown);
  var OpenNextChapter: () => void;
  var openPopupSettings:
    | ((arg0: {
        type: string;
        items: { icon: Element; title: string; onClick: () => void }[];
      }) => unknown)
    | ((
        arg0: Element,
        arg1: null,
        arg2: boolean,
        arg3: { x: number; y: number }
      ) => unknown)
    | ((arg0: Element, arg1: null, arg2: boolean) => unknown);
  var OpenPrevChapter: () => void;
  var openSidebar: boolean;
  var ORIGINAL_DATA: null;
  var page: number;
  var panelMode: boolean;
  var PanelsApps: never[];
  var PanelTabsMap: {};
  var ParentDataIds: any;
  var PieceInfo: any;
  var Playlist: any;
  var PLAYLIST_PANEL_ID: string;
  var promtInitiated: any;
  var QueuedChapterData: any;
  var RECORD_STOREKEY: string;
  var refreshScrollers: () => unknown;
  var RemoveApplication: () => void;
  var RemoveApplicationByID: (arg0: string) => unknown;
  var RemoveFloatingApp: any;
  var RemoveNowBarApp: (arg0: string) => unknown;
  var removePresentationMode: null;
  var RemoveTab: (tabId: any) => void;
  var RemoveTool: () => void;
  var RemoveWordHighlight: (config: any) => void;
  var ReplaceApplication:
    | ((
        arg0: unknown,
        arg1: { id: string; App: Element; to: string; minWidth: string }
      ) => unknown)
    | ((
        arg0: unknown,
        arg1: {
          id: string;
          App: Element;
          to: string;
          minWidth: string;
          panelKey: string;
        }
      ) => unknown);
  var ScriptureMap3DManager: Bot;
  var ScrollTimerToVerse: Timeout;
  var ScrollToVerse: (arg0: { vNumber: number }) => unknown;
  var SearchBarHideAndSeek: any;
  var selectBookSelectorBook: (arg0: null) => unknown;
  var selectedAnnot: null;
  var selectingTranslation: boolean;
  var selectionUIBehavior: {};
  var sendIcon: any;
  var SET_SHOW_CHECK:
    | ((arg0: boolean) => unknown)
    | ((arg0: number) => unknown);
  var SetActiveSettingsTab: (arg0: string) => unknown;
  var SetActiveTab: (arg0: string) => unknown;
  var SetAiTextMessages: null;
  var SetApps: StateUpdater<never[]>;
  var SetAssistantWriting: StateUpdater<boolean>;
  var SetBlinker: (arg0: {}) => unknown;
  var SetBooksOnlineUsers: StateUpdater<null>;
  var setBotId: StateUpdater<null>;
  var SetCanvasTools: null;
  var SetCurrentBook: (arg0: {
    use: string;
    first: boolean;
    type: string;
    book: string;
    bookId: string;
    chapter: number;
    translation: string;
    shortName: string;
  }) => unknown;
  var setCurrentCursor: StateUpdater<null>;
  var setCurrentExperience: (arg0: number) => unknown;
  var SetCurrentReference: StateUpdater<ReferencesInterface>;
  var setCustomScreens: StateUpdater<{ value: number }>;
  var SetDontOpenPlaylist: (arg0: boolean) => unknown;
  var SetElement: (arg0: {
    App: Element;
    data: { id: string; App: Element; to: string; minWidth: string };
  }) => unknown;
  var setEventQuery: StateUpdater<string>;
  var SetExtraHeight: StateUpdater<number>;
  var SetGlobalProfilePic: StateUpdater<undefined>;
  var SetHighlighted: StateUpdater<{}>;
  var SetHolded: (arg0: {}) => unknown;
  var SetInHold: ((arg0: {}) => unknown) | ((arg0: null) => unknown);
  var SetIsDragging: (arg0: boolean) => unknown;
  var SetIsSignedIn: (arg0: boolean) => unknown;
  var SetMapTools: null;
  var SetOnlineUsers: StateUpdater<boolean>;
  var setOpenOnMobile: (arg0: boolean) => unknown;
  var setOpenSidebar: (arg0: boolean) => unknown;
  var SETOPTIONS: (arg0: {
    type: string;
    items: (false | { icon: Element; title: string; onClick: () => void })[];
  }) => unknown;
  var SetPackageAddingOptions: StateUpdater<never[]>;
  var setPage: (arg0: number) => unknown;
  var SetPanalApp: () => void;
  var SetPlaylistForcedHeight: (arg0: number) => unknown;
  var SetQueue: boolean;
  var SetScreens: () => void;
  var SetSelected: (arg0: {}) => unknown;
  var SetSelectedVerses: (arg0: never[]) => unknown;
  var setSelectingTranslation: StateUpdater<boolean>;
  var SetShowCommands: (arg0: boolean) => unknown;
  var SetShowScreenPanelOption: (arg0: boolean) => unknown;
  var SetShowToolbar: (arg0: boolean) => unknown;
  var setSliderValue: (arg0: number) => unknown;
  var SetToolbarBackground: () => void;
  var SetTools: null;
  var SetUid: (arg0: string) => unknown;
  var SetUserWriting: StateUpdater<boolean>;
  var SetWordHighlightsBC: StateUpdater<string>;
  var SetWordHighlightsTC: StateUpdater<string>;
  var SHORTCUT_KEYS: {};
  var ShowModal: (arg0: Element) => unknown;
  var showRefModal: boolean;
  var soundThrottleLimit: {};
  var SpaceLayouts: {};
  var SpaceScreens: {};
  var StackBibleData: any;
  var StackBookData: any;
  var StackChapterData: any;
  var StackData: any;
  var StackSectionBookData: any;
  var StackSectionData: any;
  var StackTestamentData: any;
  var StartSession: () => void;
  var STUDYNOTES_PANEL_ID: string;
  var studyNotesPresent: boolean;
  var TabernacleManager: Bot;
  var TabernacleScrollToVerse: null;
  var TAPOZ_CHATBOX_UI_ID: string;
  var TapozChatboxPresent: boolean;
  var ThemeCSS: string;
  var TogglePrivateMode: () => unknown;
  var ToggleToolActive: (arg0: unknown, arg1: string) => unknown;
  var ToggleVerseHighlight: (
    arg0: unknown,
    arg1: unknown,
    arg2: unknown,
    arg3: unknown,
    arg4: boolean
  ) => unknown;
  var toolbarChanges: {};
  var ToolbarReSeedMode: (arg0: undefined) => unknown;
  var ToToggleShowInPageToolbar: (
    label: any,
    { inSet }?: { inSet?: string | undefined }
  ) => void;
  var ToToggleShowInStarterToolbar: (
    label: any,
    { inSet }?: { inSet?: string | undefined }
  ) => void;
  var TourGuideData: any;
  var UnhighlightDelayInfo: any;
  var UnHighlightVerse: (arg0: number) => unknown;
  var UpdateApplication: (
    arg0: unknown,
    arg1: { App: Element; to: string }
  ) => unknown;
  var UpdateTab:
    | ((arg0: {
        id: string;
        taken: boolean;
        data: {
          use: string;
          first: boolean;
          type: string;
          book: string;
          bookId: string;
          chapter: number;
          translation: string;
          shortName: string;
        };
      }) => unknown)
    | ((arg0: {
        id: string;
        taken: boolean;
        data: {
          use: string;
          type: string;
          book: string;
          bookId: string;
          chapter: number;
          translation: string;
          shortName: string;
        };
      }) => unknown);
  var UpdateTool: () => void;
  var VerseContextMenuOptions: {};
  var VerseSectionMap: any;
  var wordHighlights: {};
}
