import type { ArrangementInfoConfig } from "bibleVizUtils.infrastructure.models.arrangement";

export const staticArrangements: ArrangementInfoConfig[] = [
  {
    name: "traditional",
    testaments: [
      {
        name: "New Testament",
        translationKey: "new-testament",
        sections: [
          {
            name: "Apocalypse",
            translationKey: "apocalypse",
            color: "#B1B2FF",
            books: [{ bookId: "REV", type: "complete" }],
          },
          {
            name: "Letters",
            translationKey: "letters",
            color: "#AAC4FF",
            customExplodedViewScaleFactor: 8,
            customColorRange: 120,
            books: [
              {
                bookId: "JUD",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0 },
              },
              {
                bookId: "3JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0.1 },
                group: 1,
              },
              {
                bookId: "2JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: -0.125, z: 0.1 },
                group: 1,
              },
              {
                bookId: "1JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.175, y: -0.125, z: 0.1 },
                group: 1,
              },
              {
                bookId: "2PE",
                type: "complete",
                explodedViewCustomScale: { x: 0.75, y: 0.2625 },
                explodedViewPosition: { x: 0.1, y: 0.268, z: 0.19 },
                group: 2,
              },
              {
                bookId: "1PE",
                type: "complete",
                explodedViewCustomScale: { x: 0.75, y: 0.4375 },
                explodedViewPosition: { x: -0.1, y: -0.181, z: 0.19 },
                group: 2,
              },
              {
                bookId: "JAS",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.29 },
              },
              {
                bookId: "HEB",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.333 },
              },
              {
                bookId: "PHM",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.376 },
              },
              {
                bookId: "TIT",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.42 },
              },
              {
                bookId: "2TI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: 0.1, y: 0.225, z: 0.51 },
                group: 3,
              },
              {
                bookId: "1TI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: -0.1, y: -0.225, z: 0.51 },
                group: 3,
              },
              {
                bookId: "2TH",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.6 },
                explodedViewPosition: { x: 0.225, y: 0.05, z: 0.59 },
                group: 4,
              },
              {
                bookId: "1TH",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.6 },
                explodedViewPosition: { x: -0.225, y: -0.05, z: 0.59 },
                group: 4,
              },
              {
                bookId: "COL",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.69 },
              },
              {
                bookId: "PHP",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.733 },
              },
              {
                bookId: "EPH",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.776 },
              },
              {
                bookId: "GAL",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.82 },
              },
              {
                bookId: "2CO",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: 0.1, y: 0.225, z: 0.91 },
                group: 5,
              },
              {
                bookId: "1CO",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: -0.1, y: -0.225, z: 0.91 },
                group: 5,
              },
              {
                bookId: "ROM",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 1 },
              },
            ],
          },
          {
            name: "History",
            translationKey: "history",
            color: "#a0aeeb",
            books: [{ bookId: "ACT", type: "complete" }],
          },
          {
            name: "Gospels",
            translationKey: "gospels",
            color: "#a4accf",
            customExplodedViewScaleFactor: 3,
            books: [
              {
                bookId: "JHN",
                type: "complete",
                explodedViewPosition: { x: 0.3, y: 0, z: 0.1 },
              },
              {
                bookId: "LUK",
                type: "complete",
                explodedViewPosition: { x: 0, y: -0.3, z: 0.36 },
              },
              {
                bookId: "MRK",
                type: "complete",
                explodedViewPosition: { x: -0.3, y: 0, z: 0.632 },
              },
              {
                bookId: "MAT",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0.3, z: 0.9 },
              },
            ],
          },
        ],
      },
      {
        name: "Old Testament",
        translationKey: "old-testament",
        sections: [
          {
            name: "Prophets",
            translationKey: "prophets",
            color: "#EF9595",
            customExplodedViewScaleFactor: 3,
            customColorRange: 80,
            books: [
              {
                bookId: "MAL",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0 },
              },
              {
                bookId: "ZEC",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: 0.175, y: -0.125, z: 0 },
              },
              {
                bookId: "HAG",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: -0.325, y: -0.125, z: 0 },
              },
              {
                bookId: "ZEP",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0.12 },
              },
              {
                bookId: "HAB",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: -0.125, z: 0.12 },
              },
              {
                bookId: "NAH",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.175, y: -0.125, z: 0.12 },
              },
              {
                bookId: "MIC",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: -0.375, z: 0.24 },
              },
              {
                bookId: "JON",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: 0.125, z: 0.24 },
              },
              {
                bookId: "OBA",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.175, y: 0.125, z: 0.24 },
              },
              {
                bookId: "AMO",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: -0.375, z: 0.36 },
              },
              {
                bookId: "JOL",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: 0.175, y: 0.125, z: 0.36 },
              },
              {
                bookId: "HOS",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: -0.325, y: 0.125, z: 0.36 },
              },
              {
                bookId: "DAN",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.55 },
              },
              {
                bookId: "EZK",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.65 },
              },
              {
                bookId: "LAM",
                type: "complete",
                explodedViewCustomScale: { x: 0.4, y: 0.6 },
                explodedViewPosition: { x: 0.25, y: 0.05, z: 0.77 },
              },
              {
                bookId: "JER",
                type: "complete",
                explodedViewCustomScale: { x: 0.4, y: 0.6 },
                explodedViewPosition: { x: -0.25, y: -0.05, z: 0.79 },
              },
              {
                bookId: "ISA",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.95 },
              },
            ],
          },
          {
            name: "Wisdom",
            translationKey: "wisdom",
            color: "#EFB495",
            customExplodedViewScaleFactor: 2.5,
            customColorRange: 80,
            books: [
              {
                bookId: "SNG",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.9 },
                explodedViewPosition: { x: 0.15, y: 0, z: 0 },
              },
              {
                bookId: "ECC",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.9 },
                explodedViewPosition: { x: 0, y: 0, z: 0.075 },
              },
              {
                bookId: "PRO",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.9 },
                explodedViewPosition: { x: -0.15, y: 0, z: 0.1875 },
              },
              {
                bookId: "5PS",
                type: "subset",
                translationRule: "5 {name}",
                completeBookId: "PSA",
                startIndex: 106,
                endIndex: 149,
                explodedViewPosition: { x: -0.3, y: -0.35, z: 0.42 },
                group: 4,
              },
              {
                bookId: "4PS",
                type: "subset",
                translationRule: "4 {name}",
                completeBookId: "PSA",
                startIndex: 89,
                endIndex: 105,
                explodedViewPosition: { x: 0.3, y: -0.35, z: 0.46 },
                group: 4,
              },
              {
                bookId: "3PS",
                type: "subset",
                translationRule: "3 {name}",
                completeBookId: "PSA",
                startIndex: 72,
                endIndex: 88,
                explodedViewPosition: { x: 0.5, y: 0.25, z: 0.5 },
                group: 4,
              },
              {
                bookId: "2PS",
                type: "subset",
                translationRule: "2 {name}",
                completeBookId: "PSA",
                startIndex: 41,
                endIndex: 71,
                explodedViewPosition: { x: 0, y: 0.35, z: 0.54 },
                group: 4,
              },
              {
                bookId: "1PS",
                type: "subset",
                translationRule: "1 {name}",
                completeBookId: "PSA",
                startIndex: 0,
                endIndex: 40,
                explodedViewPosition: { x: -0.5, y: 0.25, z: 0.58 },
                group: 4,
              },
              {
                bookId: "JOB",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.9 },
              },
            ],
          },
          {
            name: "History",
            translationKey: "history",
            color: "#EFD595",
            customExplodedViewScaleFactor: 2.5,
            customColorRange: 80,
            books: [
              {
                bookId: "EST",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0 },
              },
              {
                bookId: "NEH",
                type: "complete",
                explodedViewCustomScale: { x: 1.1, y: 0.35 },
                explodedViewPosition: { x: 0.1, y: -0.2, z: 0.14 },
              },
              {
                bookId: "EZR",
                type: "complete",
                explodedViewCustomScale: { x: 1.1, y: 0.35 },
                explodedViewPosition: { x: -0.1, y: 0.2, z: 0.16 },
              },
              {
                bookId: "2CH",
                type: "complete",
                explodedViewPosition: { x: 0.35, y: 0.05, z: 0.37 },
                group: 3,
              },
              {
                bookId: "1CH",
                type: "complete",
                explodedViewPosition: { x: -0.35, y: -0.05, z: 0.39 },
                group: 3,
              },
              {
                bookId: "2KI",
                type: "complete",
                explodedViewPosition: { x: 0.35, y: 0.05, z: 0.49 },
                group: 2,
              },
              {
                bookId: "1KI",
                type: "complete",
                explodedViewPosition: { x: -0.35, y: -0.05, z: 0.51 },
                group: 2,
              },
              {
                bookId: "2SA",
                type: "complete",
                explodedViewPosition: { x: 0.35, y: 0.05, z: 0.61 },
                group: 1,
              },
              {
                bookId: "1SA",
                type: "complete",
                explodedViewPosition: { x: -0.35, y: -0.05, z: 0.63 },
                group: 1,
              },
              {
                bookId: "RUT",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.8 },
              },
              {
                bookId: "JDG",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.9 },
              },
              {
                bookId: "JOS",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 1 },
              },
            ],
          },
          {
            name: "Law",
            translationKey: "law",
            color: "#E5E67E",
            customExplodedViewScaleFactor: 2.5,
            books: [
              {
                bookId: "DEU",
                type: "complete",
                explodedViewPosition: { x: 0.4, y: 0.4, z: 0 },
              },
              {
                bookId: "NUM",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.25 },
              },
              {
                bookId: "LEV",
                type: "complete",
                explodedViewPosition: { x: -0.4, y: -0.4, z: 0.5 },
              },
              {
                bookId: "EXO",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.75 },
              },
              {
                bookId: "GEN",
                type: "complete",
                explodedViewPosition: { x: 0.4, y: 0.4, z: 1 },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "tanak",
    testaments: [
      {
        name: "New Testament",
        translationKey: "new-testament",
        sections: [
          {
            name: "Apocalypse",
            translationKey: "apocalypse",
            color: "#B1B2FF",
            books: [
              {
                bookId: "REV",
                type: "complete",
              },
            ],
          },
          {
            name: "Letters",
            translationKey: "letters",
            color: "#AAC4FF",
            customExplodedViewScaleFactor: 8,
            customColorRange: 120,
            books: [
              {
                bookId: "JUD",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0 },
              },
              {
                bookId: "3JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0.1 },
                group: 1,
              },
              {
                bookId: "2JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: -0.125, z: 0.1 },
                group: 1,
              },
              {
                bookId: "1JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.175, y: -0.125, z: 0.1 },
                group: 1,
              },
              {
                bookId: "2PE",
                type: "complete",
                explodedViewCustomScale: { x: 0.75, y: 0.2625 },
                explodedViewPosition: { x: 0.1, y: 0.268, z: 0.19 },
                group: 2,
              },
              {
                bookId: "1PE",
                type: "complete",
                explodedViewCustomScale: { x: 0.75, y: 0.4375 },
                explodedViewPosition: { x: -0.1, y: -0.181, z: 0.19 },
                group: 2,
              },
              {
                bookId: "JAS",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.29 },
              },
              {
                bookId: "HEB",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.333 },
              },
              {
                bookId: "PHM",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.376 },
              },
              {
                bookId: "TIT",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.42 },
              },
              {
                bookId: "2TI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: 0.1, y: 0.225, z: 0.51 },
                group: 3,
              },
              {
                bookId: "1TI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: -0.1, y: -0.225, z: 0.51 },
                group: 3,
              },
              {
                bookId: "2TH",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.6 },
                explodedViewPosition: { x: 0.225, y: 0.05, z: 0.59 },
                group: 4,
              },
              {
                bookId: "1TH",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.6 },
                explodedViewPosition: { x: -0.225, y: -0.05, z: 0.59 },
                group: 4,
              },
              {
                bookId: "COL",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.69 },
              },
              {
                bookId: "PHP",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.733 },
              },
              {
                bookId: "EPH",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.776 },
              },
              {
                bookId: "GAL",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.82 },
              },
              {
                bookId: "2CO",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: 0.1, y: 0.225, z: 0.91 },
                group: 5,
              },
              {
                bookId: "1CO",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: -0.1, y: -0.225, z: 0.91 },
                group: 5,
              },
              {
                bookId: "ROM",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 1 },
              },
            ],
          },
          {
            name: "History",
            translationKey: "history",
            color: "#a0aeeb",
            books: [
              {
                bookId: "ACT",
                type: "complete",
              },
            ],
          },
          {
            name: "Gospels",
            translationKey: "gospels",
            color: "#a4accf",
            customExplodedViewScaleFactor: 3,
            books: [
              {
                bookId: "JHN",
                type: "complete",
                explodedViewPosition: { x: 0.3, y: 0, z: 0.1 },
              },
              {
                bookId: "LUK",
                type: "complete",
                explodedViewPosition: { x: 0, y: -0.3, z: 0.36 },
              },
              {
                bookId: "MRK",
                type: "complete",
                explodedViewPosition: { x: -0.3, y: 0, z: 0.632 },
              },
              {
                bookId: "MAT",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0.3, z: 0.9 },
              },
            ],
          },
        ],
      },
      {
        name: "Old Testament",
        translationKey: "old-testament",
        sections: [
          {
            name: "Writings",
            translationKey: "writings",
            color: "#708871",
            customExplodedViewScaleFactor: 3,
            customColorRange: 80,
            books: [
              {
                bookId: "2CH",
                type: "complete",
                explodedViewPosition: { x: 0.35, y: 0.05, z: 0.01 },
                group: 3,
              },
              {
                bookId: "1CH",
                type: "complete",
                explodedViewPosition: { x: -0.35, y: -0.05, z: 0.01 },
                group: 3,
              },
              {
                bookId: "NEH",
                type: "complete",
                explodedViewPosition: { x: 0.35, y: 0.05, z: 0.1 },
                group: 2,
              },
              {
                bookId: "EZR",
                type: "complete",
                group: 2,
                explodedViewPosition: { x: -0.35, y: -0.05, z: 0.1 },
              },
              {
                bookId: "DAN",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.22 },
              },
              {
                bookId: "EST",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.28 },
              },
              {
                bookId: "ECC",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.34 },
              },
              {
                bookId: "LAM",
                type: "complete",

                explodedViewPosition: { x: 0, y: -0, z: 0.39 },
              },
              {
                bookId: "RUT",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.44 },
              },
              {
                bookId: "SNG",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.5 },
              },
              {
                bookId: "JOB",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.56 },
              },
              {
                bookId: "PRO",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.63 },
              },
              {
                bookId: "5PS",
                type: "subset",
                translationRule: "5 {name}",
                completeBookId: "PSA",
                startIndex: 106,
                endIndex: 149,
                explodedViewPosition: { x: -0.3, y: -0.35, z: 0.79 },
                group: 4,
              },
              {
                bookId: "4PS",
                type: "subset",
                translationRule: "4 {name}",
                completeBookId: "PSA",
                startIndex: 89,
                endIndex: 105,
                explodedViewPosition: { x: 0.3, y: -0.35, z: 0.82 },
                group: 4,
              },
              {
                bookId: "3PS",
                type: "subset",
                translationRule: "3 {name}",
                completeBookId: "PSA",
                startIndex: 72,
                endIndex: 88,
                explodedViewPosition: { x: 0.5, y: 0.25, z: 0.83 },
                group: 4,
              },
              {
                bookId: "2PS",
                type: "subset",
                translationRule: "2 {name}",
                completeBookId: "PSA",
                startIndex: 41,
                endIndex: 71,
                explodedViewPosition: { x: 0, y: 0.35, z: 0.85 },
                group: 4,
              },
              {
                bookId: "1PS",
                type: "subset",
                translationRule: "1 {name}",
                completeBookId: "PSA",
                startIndex: 0,
                endIndex: 40,
                explodedViewPosition: { x: -0.5, y: 0.25, z: 0.89 },
                group: 4,
              },
            ],
          },
          {
            name: "Prophets",
            translationKey: "prophets",
            color: "#bec6a0",
            customExplodedViewScaleFactor: 2.5,
            customColorRange: 80,
            books: [
              {
                bookId: "MAL",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0.02 },
              },
              {
                bookId: "ZEC",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: 0.175, y: -0.125, z: 0.02 },
              },
              {
                bookId: "HAG",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: -0.325, y: -0.125, z: 0.02 },
              },
              {
                bookId: "ZEP",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0.09 },
              },
              {
                bookId: "HAB",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: -0.125, z: 0.09 },
              },
              {
                bookId: "NAH",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.175, y: -0.125, z: 0.09 },
              },
              {
                bookId: "MIC",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: -0.375, z: 0.16 },
              },
              {
                bookId: "JON",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: 0.125, z: 0.16 },
              },
              {
                bookId: "OBA",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.175, y: 0.125, z: 0.16 },
              },
              {
                bookId: "AMO",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: -0.375, z: 0.23 },
              },
              {
                bookId: "JOL",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: 0.175, y: 0.125, z: 0.23 },
              },
              {
                bookId: "HOS",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: -0.325, y: 0.125, z: 0.23 },
              },

              {
                bookId: "EZK",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.33 },
              },
              {
                bookId: "JER",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.43 },
              },
              {
                bookId: "ISA",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.56 },
              },
              {
                bookId: "2KI",
                type: "complete",
                explodedViewPosition: { x: 0.35, y: 0.05, z: 0.68 },
                group: 2,
              },
              {
                bookId: "1KI",
                type: "complete",
                explodedViewPosition: { x: -0.35, y: -0.05, z: 0.68 },
                group: 2,
              },
              {
                bookId: "2SA",
                type: "complete",
                explodedViewPosition: { x: 0.35, y: 0.05, z: 0.78 },
                group: 1,
              },
              {
                bookId: "1SA",
                type: "complete",
                explodedViewPosition: { x: -0.35, y: -0.05, z: 0.78 },
                group: 1,
              },
              {
                bookId: "JDG",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.89 },
              },
              {
                bookId: "JOS",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.98 },
              },
            ],
          },
          {
            name: "Torah",
            translationKey: "torah",
            color: "#fef3e2",
            customExplodedViewScaleFactor: 2.5,
            books: [
              {
                bookId: "DEU",
                type: "complete",
                explodedViewPosition: { x: 0.4, y: 0.4, z: 0 },
              },
              {
                bookId: "NUM",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.25 },
              },
              {
                bookId: "LEV",
                type: "complete",
                explodedViewPosition: { x: -0.4, y: -0.4, z: 0.5 },
              },
              {
                bookId: "EXO",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.75 },
              },
              {
                bookId: "GEN",
                type: "complete",
                explodedViewPosition: { x: 0.4, y: 0.4, z: 1 },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Chronological",
    testaments: [
      {
        name: "New Testament",
        translationKey: "new-testament",
        sections: [
          {
            name: "Chronological NT",
            translationKey: "chronological-nt",
            color: "#d5d5d5",
            customExplodedViewScaleFactor: 4.9,
            customColorRange: 80,
            books: [
              {
                bookId: "REV",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: -0.03 },
                customColor: "#8DC53E",
              },
              {
                bookId: "3JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0.02 },
                group: 1,
                customColor: "#8DC53E",
              },
              {
                bookId: "2JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: -0.125, z: 0.02 },
                group: 1,
                customColor: "#8DC53E",
              },
              {
                bookId: "1JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.175, y: -0.125, z: 0.02 },
                group: 1,
                customColor: "#8DC53E",
              },
              {
                bookId: "JUD",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.08 },
                customColor: "#8DC53E",
              },
              {
                bookId: "2TI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: 0.1, y: 0.225, z: 0.1 },

                customColor: "#FEDF01",
              },
              {
                bookId: "TIT",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.15 },
                customColor: "#FEDF01",
              },
              {
                bookId: "1TI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: -0.1, y: -0.225, z: 0.2 },

                customColor: "#FEDF01",
              },
              {
                bookId: "HEB",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.25 },
                customColor: "#8DC53E",
              },
              {
                bookId: "2PE",
                type: "complete",
                explodedViewCustomScale: { x: 1, y: 0.35 },
                explodedViewPosition: { x: 0, y: 0.35, z: 0.3 },
                group: 2,
                customColor: "#8DC53E",
              },
              {
                bookId: "1PE",
                type: "complete",
                explodedViewCustomScale: { x: 1, y: 0.35 },
                explodedViewPosition: { x: 0, y: -0.2, z: 0.3 },
                group: 2,
                customColor: "#8DC53E",
              },
              {
                bookId: "PHP",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.35 },
                customColor: "#FFDE00",
              },
              {
                bookId: "EPH",
                type: "complete",

                explodedViewPosition: { x: 0, y: -0, z: 0.4 },

                customColor: "#FFDE00",
              },
              {
                bookId: "PHM",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.45 },

                customColor: "#FFDE00",
              },
              {
                bookId: "COL",
                type: "complete",

                explodedViewPosition: { x: -0, y: 0, z: 0.5 },

                customColor: "#FFDE00",
              },
              {
                bookId: "JAS",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.55 },

                customColor: "#8DC53E",
              },
              {
                bookId: "ROM",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.6 },

                customColor: "#FFDE00",
              },
              {
                bookId: "GAL",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.65 },

                customColor: "#FFDE00",
              },
              {
                bookId: "2CO",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0.35, z: 0.7 },
                group: 5,

                explodedViewCustomScale: { x: 1, y: 0.35 },
                customColor: "#FFDE00",
              },
              {
                bookId: "1CO",
                type: "complete",
                explodedViewCustomScale: { x: 1, y: 0.35 },
                explodedViewPosition: { x: 0, y: -0.15, z: 0.7 },
                group: 5,
                customColor: "#FFDE00",
              },
              {
                bookId: "2TH",
                type: "complete",
                explodedViewCustomScale: { x: 0.45, y: 1 },
                explodedViewPosition: { x: 0.5, y: 0, z: 0.75 },
                group: 4,
                customColor: "#FFDE00",
              },
              {
                bookId: "1TH",
                type: "complete",
                group: 4,
                explodedViewPosition: { x: -0, y: 0, z: 0.75 },
                explodedViewCustomScale: { x: 0.45, y: 1 },
                customColor: "#FFDE00",
              },
              {
                bookId: "ACT",
                type: "complete",
                explodedViewPosition: { x: 0.2, y: 0, z: 0.8 },
                customColor: "#FAA51A",
              },
              {
                bookId: "JHN",
                type: "complete",
                explodedViewPosition: { x: 0.2, y: 0, z: 0.85 },
                customColor: "#FAA51A",
              },
              {
                bookId: "LUK",
                type: "complete",
                explodedViewPosition: { x: 0, y: -0.1, z: 0.9 },
                customColor: "#FAA51A",
              },
              {
                bookId: "MRK",
                type: "complete",
                explodedViewPosition: { x: -0.1, y: -0.01, z: 0.95 },
                customColor: "#FAA51A",
              },
              {
                bookId: "MAT",
                type: "complete",
                explodedViewPosition: { x: 0.2, y: 0.2, z: 1 },
                customColor: "#FAA51A",
              },
            ],
          },
        ],
      },
      {
        name: "Old Testament",
        translationKey: "old-testament",
        sections: [
          {
            name: "Chronological OT",
            translationKey: "chronological-ot",
            color: "#d5d5d5",
            customExplodedViewScaleFactor: 2.8,
            customColorRange: 80,
            books: [
              {
                bookId: "MAL",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 0.25 },
                explodedViewPosition: { x: 0, y: -0.475, z: -0.01 },
                customColor: "#DAE3F4",
              },
              {
                bookId: "ZEC",
                type: "complete",
                explodedViewCustomScale: { x: 0.65, y: 0.75 },
                explodedViewPosition: { x: 0.275, y: 0.225, z: -0.01 },
                customColor: "#DAE3F4",
              },
              {
                bookId: "HAG",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.75 },
                explodedViewPosition: { x: -0.425, y: 0.225, z: -0.01 },
                customColor: "#DAE3F4",
              },
              {
                bookId: "NEH",
                type: "complete",
                explodedViewCustomScale: { x: 1.3, y: 1.3 },
                explodedViewPosition: { x: 0, y: -0, z: 0.02 },
                customColor: "#DAE3F4",
              },
              {
                bookId: "EST",
                type: "complete",
                explodedViewCustomScale: { x: 1.3, y: 1.3 },
                explodedViewPosition: { x: 0, y: 0, z: 0.05 },
                customColor: "#DAE3F4",
              },
              {
                bookId: "EZR",
                type: "complete",
                explodedViewCustomScale: { x: 1.3, y: 1.3 },
                explodedViewPosition: { x: -0, y: 0, z: 0.09 },
                customColor: "#DAE3F4",
              },
              {
                bookId: "DAN",
                type: "complete",
                explodedViewCustomScale: { x: 1.3, y: 1.3 },
                explodedViewPosition: { x: 0, y: 0, z: 0.12 },
                customColor: "#8FABDD",
              },
              {
                bookId: "EZK",
                type: "complete",
                explodedViewCustomScale: { x: 1.3, y: 1.3 },
                explodedViewPosition: { x: 0, y: 0, z: 0.15 },
                customColor: "#8FABDD",
              },
              {
                bookId: "ZEP",
                type: "complete",
                explodedViewCustomScale: { x: 1, y: 0.25 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0.18 },
                customColor: "#8FABDD",
              },
              {
                bookId: "HAB",
                type: "complete",
                explodedViewCustomScale: { x: 0.28, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: -0.225, z: 0.18 },
                customColor: "#8FABDD",
              },
              {
                bookId: "NAH",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.32, y: -0.225, z: 0.18 },
                customColor: "#8FABDD",
              },
              {
                bookId: "MIC",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 0.25 },
                explodedViewPosition: { x: 0, y: -0.475, z: 0.22 },
                customColor: "#8FABDD",
              },
              {
                bookId: "JON",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.75 },
                explodedViewPosition: { x: 0.39, y: 0.125, z: 0.22 },
                customColor: "#8FABDD",
              },
              {
                bookId: "OBA",
                type: "complete",
                explodedViewCustomScale: { x: 0.65, y: 0.75 },
                explodedViewPosition: { x: -0.275, y: 0.125, z: 0.22 },
                customColor: "#8FABDD",
              },
              {
                bookId: "AMO",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 0.25 },
                explodedViewPosition: { x: 0, y: -0.475, z: 0.26 },
                customColor: "#8FABDD",
              },
              {
                bookId: "JOL",
                type: "complete",
                explodedViewCustomScale: { x: 0.65, y: 0.75 },
                explodedViewPosition: { x: 0.275, y: 0.225, z: 0.26 },
                customColor: "#8FABDD",
              },
              {
                bookId: "HOS",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.75 },
                explodedViewPosition: { x: -0.425, y: 0.225, z: 0.26 },
                customColor: "#8FABDD",
              },
              {
                bookId: "LAM",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 1.2, z: 1.7 },
                explodedViewPosition: { x: 0, y: 0, z: 0.3 },
                customColor: "#8FABDD",
              },
              {
                bookId: "JER",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 1.2, z: 1.7 },
                explodedViewPosition: { x: -0, y: -0, z: 0.33 },
                customColor: "#8FABDD",
              },
              {
                bookId: "ISA",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 1.2, z: 1.7 },
                explodedViewPosition: { x: -0, y: -0, z: 0.36 },
                customColor: "#8FABDD",
              },
              {
                bookId: "2CH",
                type: "complete",
                explodedViewPosition: { x: 0.55, y: 0.05, z: 0.42 },
                customColor: "#DAE3F4",
              },
              {
                bookId: "2KI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 1, z: 1.7 },
                explodedViewPosition: { x: 0.5, y: 0.05, z: 0.45 },
                group: 2,
                customColor: "#DAE3F4",
              },
              {
                bookId: "1KI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 1, z: 1.7 },
                explodedViewPosition: { x: -0.6, y: -0, z: 0.45 },
                group: 2,
                customColor: "#DAE3F4",
              },
              {
                bookId: "ECC",
                type: "complete",
                explodedViewCustomScale: { x: 1.4, y: 1.4 },
                customColor: "#BEC6A0",
                explodedViewPosition: { x: 0, y: 0, z: 0.49 },
              },
              {
                bookId: "PRO",
                type: "complete",
                customColor: "#BEC6A0",
                explodedViewCustomScale: { x: 1.4, y: 1.4 },
                explodedViewPosition: { x: 0, y: 0, z: 0.52 },
              },
              {
                bookId: "SNG",
                type: "complete",
                explodedViewCustomScale: { x: 1.4, y: 1.4 },
                explodedViewPosition: { x: 0, y: 0, z: 0.55 },
                customColor: "#BEC6A0",
              },
              {
                bookId: "5PS",
                type: "subset",
                translationRule: "5 {name}",
                completeBookId: "PSA",
                startIndex: 106,
                endIndex: 149,
                explodedViewPosition: { x: -0.8, y: -0.2, z: 0.6 },
                group: 4,
                customColor: "#BEC6A0",
              },
              {
                bookId: "4PS",
                type: "subset",
                translationRule: "4 {name}",
                completeBookId: "PSA",
                startIndex: 89,
                endIndex: 105,
                explodedViewPosition: { x: 0.3, y: -0.35, z: 0.61 },
                group: 4,
                customColor: "#BEC6A0",
              },
              {
                bookId: "3PS",
                type: "subset",
                translationRule: "3 {name}",
                completeBookId: "PSA",
                startIndex: 72,
                endIndex: 88,
                explodedViewPosition: { x: 1, y: 0, z: 0.62 },
                group: 4,
                customColor: "#BEC6A0",
              },
              {
                bookId: "2PS",
                type: "subset",
                translationRule: "2 {name}",
                completeBookId: "PSA",
                startIndex: 41,
                endIndex: 71,
                explodedViewPosition: { x: 0.3, y: 0.35, z: 0.63 },
                group: 4,
                customColor: "#BEC6A0",
              },
              {
                bookId: "1PS",
                type: "subset",
                translationRule: "1 {name}",
                completeBookId: "PSA",
                startIndex: 0,
                endIndex: 40,
                explodedViewPosition: { x: -0.5, y: 0.25, z: 0.64 },
                group: 4,
                customColor: "#BEC6A0",
              },
              {
                bookId: "1CH",
                type: "complete",
                explodedViewPosition: { x: -0.55, y: -0.05, z: 0.69 },
                customColor: "#DAE3F4",
              },
              {
                bookId: "2SA",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 1, z: 1.7 },
                explodedViewPosition: { x: 0.55, y: 0.05, z: 0.72 },
                group: 1,
                customColor: "#DAE3F4",
              },
              {
                bookId: "1SA",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 1 },
                explodedViewPosition: { x: -0.55, y: -0.05, z: 0.72 },
                group: 1,
                customColor: "#DAE3F4",
              },
              {
                bookId: "RUT",
                type: "complete",
                explodedViewCustomScale: { x: 1.4, y: 1.4 },
                explodedViewPosition: { x: 0, y: 0, z: 0.75 },
                customColor: "#DAE3F4",
              },
              {
                bookId: "JDG",
                type: "complete",
                explodedViewCustomScale: { x: 1.4, y: 1.4 },
                explodedViewPosition: { x: 0, y: 0, z: 0.77 },
                customColor: "#DAE3F4",
              },
              {
                bookId: "JOS",
                type: "complete",
                explodedViewCustomScale: { x: 1.4, y: 1.4, z: 1 },
                explodedViewPosition: { x: 0, y: 0, z: 0.8 },
                customColor: "#DAE3F4",
              },
              {
                bookId: "DEU",
                type: "complete",
                explodedViewPosition: { x: -0.35, y: 0.8, z: 0.837 },
                customColor: "#FEE799",
              },
              {
                bookId: "NUM",
                type: "complete",
                explodedViewPosition: { x: -0.6, y: 0.1, z: 0.867 },
                customColor: "#FEE799",
              },
              {
                bookId: "LEV",
                type: "complete",
                explodedViewPosition: { x: -0.4, y: -0.4, z: 0.91 },
                customColor: "#FEE799",
              },
              {
                bookId: "EXO",
                type: "complete",
                explodedViewPosition: { x: -0.3, y: -0.3, z: 0.94 },
                customColor: "#FEE799",
              },
              {
                bookId: "JOB",
                type: "complete",
                customColor: "#BEC6A0",
                explodedViewPosition: { x: 0.6, y: 0.4, z: 0.97 },
              },
              {
                bookId: "GEN",
                type: "complete",

                explodedViewPosition: { x: 0.2, y: 0.4, z: 1 },
                customColor: "#FEE799",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Chronological Alternative",
    testaments: [
      {
        name: "New Testament",
        translationKey: "new-testament",
        sections: [
          {
            name: "Chronological NT",
            translationKey: "chronological-nt",
            color: "#2596be",
            customExplodedViewScaleFactor: 4.9,
            customColorRange: 80,
            books: [
              {
                bookId: "REV",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: -0.03 },
              },
              {
                bookId: "3JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0.02 },
                group: 1,
              },
              {
                bookId: "2JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: -0.125, z: 0.02 },
                group: 1,
              },
              {
                bookId: "1JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.175, y: -0.125, z: 0.02 },
                group: 1,
              },
              {
                bookId: "JUD",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.08 },
              },
              {
                bookId: "2TI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: 0.1, y: 0.225, z: 0.1 },
              },
              {
                bookId: "TIT",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.15 },
              },
              {
                bookId: "1TI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: -0.1, y: -0.225, z: 0.2 },
              },
              {
                bookId: "HEB",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.25 },
              },
              {
                bookId: "2PE",
                type: "complete",
                explodedViewCustomScale: { x: 1, y: 0.35 },
                explodedViewPosition: { x: 0, y: 0.35, z: 0.3 },
                group: 2,
              },
              {
                bookId: "1PE",
                type: "complete",
                explodedViewCustomScale: { x: 1, y: 0.35 },
                explodedViewPosition: { x: 0, y: -0.2, z: 0.3 },
                group: 2,
              },
              {
                bookId: "PHP",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.35 },
              },
              {
                bookId: "EPH",
                type: "complete",

                explodedViewPosition: { x: 0, y: -0, z: 0.4 },
              },
              {
                bookId: "PHM",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.45 },
              },
              {
                bookId: "COL",
                type: "complete",

                explodedViewPosition: { x: -0, y: 0, z: 0.5 },
              },
              {
                bookId: "JAS",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.55 },
              },
              {
                bookId: "ROM",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.6 },
              },
              {
                bookId: "GAL",
                type: "complete",

                explodedViewPosition: { x: 0, y: 0, z: 0.65 },
              },
              {
                bookId: "2CO",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0.35, z: 0.7 },
                group: 5,

                explodedViewCustomScale: { x: 1, y: 0.35 },
              },
              {
                bookId: "1CO",
                type: "complete",
                explodedViewCustomScale: { x: 1, y: 0.35 },
                explodedViewPosition: { x: 0, y: -0.15, z: 0.7 },
                group: 5,
              },
              {
                bookId: "2TH",
                type: "complete",
                explodedViewCustomScale: { x: 0.45, y: 1 },
                explodedViewPosition: { x: 0.5, y: 0, z: 0.75 },
                group: 4,
              },
              {
                bookId: "1TH",
                type: "complete",
                group: 4,
                explodedViewPosition: { x: -0, y: 0, z: 0.75 },
                explodedViewCustomScale: { x: 0.45, y: 1 },
              },
              {
                bookId: "ACT",
                type: "complete",
                explodedViewPosition: { x: 0.2, y: 0, z: 0.8 },
              },
              {
                bookId: "JHN",
                type: "complete",
                explodedViewPosition: { x: 0.2, y: 0, z: 0.85 },
              },
              {
                bookId: "LUK",
                type: "complete",
                explodedViewPosition: { x: 0, y: -0.1, z: 0.9 },
              },
              {
                bookId: "MRK",
                type: "complete",
                explodedViewPosition: { x: -0.1, y: -0.01, z: 0.95 },
              },
              {
                bookId: "MAT",
                type: "complete",
                explodedViewPosition: { x: 0.2, y: 0.2, z: 1 },
              },
            ],
          },
        ],
      },
      {
        name: "Old Testament",
        translationKey: "old-testament",
        sections: [
          {
            name: "Chronological OT",
            translationKey: "chronological-ot",
            color: "#708871",
            customExplodedViewScaleFactor: 2.8,
            customColorRange: 80,
            books: [
              {
                bookId: "MAL",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 0.25 },
                explodedViewPosition: { x: 0, y: -0.475, z: -0.01 },
              },
              {
                bookId: "ZEC",
                type: "complete",
                explodedViewCustomScale: { x: 0.65, y: 0.75 },
                explodedViewPosition: { x: 0.275, y: 0.225, z: -0.01 },
              },
              {
                bookId: "HAG",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.75 },
                explodedViewPosition: { x: -0.425, y: 0.225, z: -0.01 },
              },
              {
                bookId: "NEH",
                type: "complete",
                explodedViewCustomScale: { x: 1.3, y: 1.3 },
                explodedViewPosition: { x: 0, y: -0, z: 0.02 },
              },
              {
                bookId: "EST",
                type: "complete",
                explodedViewCustomScale: { x: 1.3, y: 1.3 },
                explodedViewPosition: { x: 0, y: 0, z: 0.05 },
              },
              {
                bookId: "EZR",
                type: "complete",
                explodedViewCustomScale: { x: 1.3, y: 1.3 },
                explodedViewPosition: { x: -0, y: 0, z: 0.09 },
              },
              {
                bookId: "DAN",
                type: "complete",
                explodedViewCustomScale: { x: 1.3, y: 1.3 },
                explodedViewPosition: { x: 0, y: 0, z: 0.12 },
              },
              {
                bookId: "EZK",
                type: "complete",
                explodedViewCustomScale: { x: 1.3, y: 1.3 },
                explodedViewPosition: { x: 0, y: 0, z: 0.15 },
              },
              {
                bookId: "ZEP",
                type: "complete",
                explodedViewCustomScale: { x: 1, y: 0.25 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0.18 },
              },
              {
                bookId: "HAB",
                type: "complete",
                explodedViewCustomScale: { x: 0.28, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: -0.225, z: 0.18 },
              },
              {
                bookId: "NAH",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.32, y: -0.225, z: 0.18 },
              },
              {
                bookId: "MIC",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 0.25 },
                explodedViewPosition: { x: 0, y: -0.475, z: 0.22 },
              },
              {
                bookId: "JON",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.75 },
                explodedViewPosition: { x: 0.39, y: 0.125, z: 0.22 },
              },
              {
                bookId: "OBA",
                type: "complete",
                explodedViewCustomScale: { x: 0.65, y: 0.75 },
                explodedViewPosition: { x: -0.275, y: 0.125, z: 0.22 },
              },
              {
                bookId: "AMO",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 0.25 },
                explodedViewPosition: { x: 0, y: -0.475, z: 0.26 },
              },
              {
                bookId: "JOL",
                type: "complete",
                explodedViewCustomScale: { x: 0.65, y: 0.75 },
                explodedViewPosition: { x: 0.275, y: 0.225, z: 0.26 },
              },
              {
                bookId: "HOS",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.75 },
                explodedViewPosition: { x: -0.425, y: 0.225, z: 0.26 },
              },
              {
                bookId: "LAM",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 1.2, z: 1.7 },
                explodedViewPosition: { x: 0, y: 0, z: 0.3 },
              },
              {
                bookId: "JER",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 1.2, z: 1.7 },
                explodedViewPosition: { x: -0, y: -0, z: 0.33 },
              },
              {
                bookId: "ISA",
                type: "complete",
                explodedViewCustomScale: { x: 1.2, y: 1.2, z: 1.7 },
                explodedViewPosition: { x: -0, y: -0, z: 0.36 },
              },
              {
                bookId: "2CH",
                type: "complete",
                explodedViewPosition: { x: 0.55, y: 0.05, z: 0.42 },
              },
              {
                bookId: "2KI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 1, z: 1.7 },
                explodedViewPosition: { x: 0.5, y: 0.05, z: 0.45 },
                group: 2,
              },
              {
                bookId: "1KI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 1, z: 1.7 },
                explodedViewPosition: { x: -0.6, y: -0, z: 0.45 },
                group: 2,
              },
              {
                bookId: "ECC",
                type: "complete",
                explodedViewCustomScale: { x: 1.4, y: 1.4 },
                explodedViewPosition: { x: 0, y: 0, z: 0.49 },
              },
              {
                bookId: "PRO",
                type: "complete",
                explodedViewCustomScale: { x: 1.4, y: 1.4 },
                explodedViewPosition: { x: 0, y: 0, z: 0.52 },
              },
              {
                bookId: "SNG",
                type: "complete",
                explodedViewCustomScale: { x: 1.4, y: 1.4 },
                explodedViewPosition: { x: 0, y: 0, z: 0.55 },
              },
              {
                bookId: "5PS",
                type: "subset",
                translationRule: "5 {name}",
                completeBookId: "PSA",
                startIndex: 106,
                endIndex: 149,
                explodedViewPosition: { x: -0.8, y: -0.2, z: 0.6 },
                group: 4,
              },
              {
                bookId: "4PS",
                type: "subset",
                translationRule: "4 {name}",
                completeBookId: "PSA",
                startIndex: 89,
                endIndex: 105,
                explodedViewPosition: { x: 0.3, y: -0.35, z: 0.61 },
                group: 4,
              },
              {
                bookId: "3PS",
                type: "subset",
                translationRule: "3 {name}",
                completeBookId: "PSA",
                startIndex: 72,
                endIndex: 88,
                explodedViewPosition: { x: 1, y: 0, z: 0.62 },
                group: 4,
              },
              {
                bookId: "2PS",
                type: "subset",
                translationRule: "2 {name}",
                completeBookId: "PSA",
                startIndex: 41,
                endIndex: 71,
                explodedViewPosition: { x: 0.3, y: 0.35, z: 0.63 },
                group: 4,
              },
              {
                bookId: "1PS",
                type: "subset",
                translationRule: "1 {name}",
                completeBookId: "PSA",
                startIndex: 0,
                endIndex: 40,
                explodedViewPosition: { x: -0.5, y: 0.25, z: 0.64 },
                group: 4,
              },
              {
                bookId: "1CH",
                type: "complete",
                explodedViewPosition: { x: -0.55, y: -0.05, z: 0.69 },
              },
              {
                bookId: "2SA",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 1, z: 1.7 },
                explodedViewPosition: { x: 0.55, y: 0.05, z: 0.72 },
                group: 1,
              },
              {
                bookId: "1SA",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 1 },
                explodedViewPosition: { x: -0.55, y: -0.05, z: 0.72 },
                group: 1,
              },
              {
                bookId: "RUT",
                type: "complete",
                explodedViewCustomScale: { x: 1.4, y: 1.4 },
                explodedViewPosition: { x: 0, y: 0, z: 0.75 },
              },
              {
                bookId: "JDG",
                type: "complete",
                explodedViewCustomScale: { x: 1.4, y: 1.4 },
                explodedViewPosition: { x: 0, y: 0, z: 0.77 },
              },
              {
                bookId: "JOS",
                type: "complete",
                explodedViewCustomScale: { x: 1.4, y: 1.4, z: 1 },
                explodedViewPosition: { x: 0, y: 0, z: 0.8 },
              },
              {
                bookId: "DEU",
                type: "complete",
                explodedViewPosition: { x: -0.35, y: 0.8, z: 0.837 },
              },
              {
                bookId: "NUM",
                type: "complete",
                explodedViewPosition: { x: -0.6, y: 0.1, z: 0.867 },
              },
              {
                bookId: "LEV",
                type: "complete",
                explodedViewPosition: { x: -0.4, y: -0.4, z: 0.91 },
              },
              {
                bookId: "EXO",
                type: "complete",
                explodedViewPosition: { x: -0.3, y: -0.3, z: 0.94 },
              },
              {
                bookId: "JOB",
                type: "complete",

                explodedViewPosition: { x: 0.6, y: 0.4, z: 0.97 },
              },
              {
                bookId: "GEN",
                type: "complete",

                explodedViewPosition: { x: 0.2, y: 0.4, z: 1 },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "PlatformerGame",
    testaments: [
      {
        name: "New Testament",
        translationKey: "new-testament",
        sections: [
          {
            name: "Apocalypse",
            translationKey: "apocalypse",
            color: "#B1B2FF",
            books: [
              {
                bookId: "REV",
                type: "complete",
              },
            ],
          },
          {
            name: "Letters",
            translationKey: "letters",
            color: "#AAC4FF",
            customExplodedViewScaleFactor: 8,
            customColorRange: 120,
            books: [
              {
                bookId: "JUD",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0 },
              },
              {
                bookId: "3JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0.1 },
                group: 1,
              },
              {
                bookId: "2JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: -0.125, z: 0.1 },
                group: 1,
              },
              {
                bookId: "1JN",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.175, y: -0.125, z: 0.1 },
                group: 1,
              },
              {
                bookId: "2PE",
                type: "complete",
                explodedViewCustomScale: { x: 0.75, y: 0.2625 },
                explodedViewPosition: { x: 0.1, y: 0.268, z: 0.19 },
                group: 2,
              },
              {
                bookId: "1PE",
                type: "complete",
                explodedViewCustomScale: { x: 0.75, y: 0.4375 },
                explodedViewPosition: { x: -0.1, y: -0.181, z: 0.19 },
                group: 2,
              },
              {
                bookId: "JAS",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.29 },
              },
              {
                bookId: "HEB",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.333 },
              },
              {
                bookId: "PHM",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.376 },
              },
              {
                bookId: "TIT",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.42 },
              },
              {
                bookId: "2TI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: 0.1, y: 0.225, z: 0.51 },
                group: 3,
              },
              {
                bookId: "1TI",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: -0.1, y: -0.225, z: 0.51 },
                group: 3,
              },
              {
                bookId: "2TH",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.6 },
                explodedViewPosition: { x: 0.225, y: 0.05, z: 0.59 },
                group: 4,
              },
              {
                bookId: "1TH",
                type: "complete",
                explodedViewCustomScale: { x: 0.35, y: 0.6 },
                explodedViewPosition: { x: -0.225, y: -0.05, z: 0.59 },
                group: 4,
              },
              {
                bookId: "COL",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.69 },
              },
              {
                bookId: "PHP",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.733 },
              },
              {
                bookId: "EPH",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.776 },
              },
              {
                bookId: "GAL",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.82 },
              },
              {
                bookId: "2CO",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: 0.1, y: 0.225, z: 0.91 },
                group: 5,
              },
              {
                bookId: "1CO",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.35 },
                explodedViewPosition: { x: -0.1, y: -0.225, z: 0.91 },
                group: 5,
              },
              {
                bookId: "ROM",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 1 },
              },
            ],
          },
          {
            name: "History",
            translationKey: "history",
            color: "#a0aeeb",
            books: [
              {
                bookId: "ACT",
                type: "complete",
              },
            ],
          },
          {
            name: "Gospels",
            translationKey: "gospels",
            color: "#a4accf",
            customExplodedViewScaleFactor: 3,
            books: [
              {
                bookId: "JHN",
                type: "complete",
                explodedViewPosition: { x: 0.3, y: 0, z: 0.1 },
              },
              {
                bookId: "LUK",
                type: "complete",
                explodedViewPosition: { x: 0, y: -0.3, z: 0.36 },
              },
              {
                bookId: "MRK",
                type: "complete",
                explodedViewPosition: { x: -0.3, y: 0, z: 0.632 },
              },
              {
                bookId: "MAT",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0.3, z: 0.9 },
                isCheckpoint: true,
              },
            ],
          },
        ],
      },
      {
        name: "Old Testament",
        translationKey: "old-testament",
        sections: [
          {
            name: "Prophets",
            translationKey: "prophets",
            color: "#EF9595",
            customExplodedViewScaleFactor: 3,
            customColorRange: 80,
            books: [
              {
                bookId: "MAL",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0 },
              },
              {
                bookId: "ZEC",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: 0.175, y: -0.125, z: 0 },
              },
              {
                bookId: "HAG",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: -0.325, y: -0.125, z: 0 },
              },
              {
                bookId: "ZEP",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: 0.375, z: 0.12 },
              },
              {
                bookId: "HAB",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: -0.125, z: 0.12 },
              },
              {
                bookId: "NAH",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.175, y: -0.125, z: 0.12 },
              },
              {
                bookId: "MIC",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: -0.375, z: 0.24 },
              },
              {
                bookId: "JON",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: 0.325, y: 0.125, z: 0.24 },
              },
              {
                bookId: "OBA",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: -0.175, y: 0.125, z: 0.24 },
              },
              {
                bookId: "AMO",
                type: "complete",
                explodedViewCustomScale: { x: 0.9, y: 0.15 },
                explodedViewPosition: { x: 0, y: -0.375, z: 0.36 },
              },
              {
                bookId: "JOL",
                type: "complete",
                explodedViewCustomScale: { x: 0.55, y: 0.65 },
                explodedViewPosition: { x: 0.175, y: 0.125, z: 0.36 },
              },
              {
                bookId: "HOS",
                type: "complete",
                explodedViewCustomScale: { x: 0.25, y: 0.65 },
                explodedViewPosition: { x: -0.325, y: 0.125, z: 0.36 },
              },
              {
                bookId: "DAN",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.55 },
              },
              {
                bookId: "EZK",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.65 },
              },
              {
                bookId: "LAM",
                type: "complete",
                explodedViewCustomScale: { x: 0.4, y: 0.6 },
                explodedViewPosition: { x: 0.25, y: 0.05, z: 0.77 },
              },
              {
                bookId: "JER",
                type: "complete",
                explodedViewCustomScale: { x: 0.4, y: 0.6 },
                explodedViewPosition: { x: -0.25, y: -0.05, z: 0.79 },
              },
              {
                bookId: "ISA",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.95 },
              },
            ],
          },
          {
            name: "Wisdom",
            translationKey: "wisdom",
            color: "#EFB495",
            customExplodedViewScaleFactor: 2.5,
            customColorRange: 80,
            books: [
              {
                bookId: "SNG",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.9 },
                explodedViewPosition: { x: 0.15, y: 0, z: 0 },
              },
              {
                bookId: "ECC",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.9 },
                explodedViewPosition: { x: 0, y: 0, z: 0.075 },
              },
              {
                bookId: "PRO",
                type: "complete",
                explodedViewCustomScale: { x: 0.7, y: 0.9 },
                explodedViewPosition: { x: -0.15, y: 0, z: 0.1875 },
              },
              {
                bookId: "5PS",
                type: "subset",
                translationRule: "5 {name}",
                completeBookId: "PSA",
                startIndex: 106,
                endIndex: 149,
                explodedViewPosition: { x: -0.3, y: -0.35, z: 0.42 },
                group: 4,
              },
              {
                bookId: "4PS",
                type: "subset",
                translationRule: "4 {name}",
                completeBookId: "PSA",
                startIndex: 89,
                endIndex: 105,
                explodedViewPosition: { x: 0.3, y: -0.35, z: 0.46 },
                group: 4,
              },
              {
                bookId: "3PS",
                type: "subset",
                translationRule: "3 {name}",
                completeBookId: "PSA",
                startIndex: 72,
                endIndex: 88,
                explodedViewPosition: { x: 0.5, y: 0.25, z: 0.5 },
                group: 4,
              },
              {
                bookId: "2PS",
                type: "subset",
                translationRule: "2 {name}",
                completeBookId: "PSA",
                startIndex: 41,
                endIndex: 71,
                explodedViewPosition: { x: 0, y: 0.35, z: 0.54 },
                group: 4,
              },
              {
                bookId: "1PS",
                type: "subset",
                translationRule: "1 {name}",
                completeBookId: "PSA",
                startIndex: 0,
                endIndex: 40,
                explodedViewPosition: { x: -0.5, y: 0.25, z: 0.58 },
                group: 4,
              },
              {
                bookId: "JOB",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.9 },
                isCheckpoint: true,
              },
            ],
          },
          {
            name: "History",
            translationKey: "history",
            color: "#EFD595",
            customExplodedViewScaleFactor: 2.5,
            customColorRange: 80,
            books: [
              {
                bookId: "EST",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0 },
              },
              {
                bookId: "NEH",
                type: "complete",
                explodedViewCustomScale: { x: 1.1, y: 0.35 },
                explodedViewPosition: { x: 0.1, y: -0.2, z: 0.14 },
              },
              {
                bookId: "EZR",
                type: "complete",
                explodedViewCustomScale: { x: 1.1, y: 0.35 },
                explodedViewPosition: { x: -0.1, y: 0.2, z: 0.16 },
              },
              {
                bookId: "2CH",
                type: "complete",
                explodedViewPosition: { x: 0.35, y: 0.05, z: 0.37 },
                group: 3,
              },
              {
                bookId: "1CH",
                type: "complete",
                explodedViewPosition: { x: -0.35, y: -0.05, z: 0.39 },
                group: 3,
              },
              {
                bookId: "2KI",
                type: "complete",
                explodedViewPosition: { x: 0.35, y: 0.05, z: 0.49 },
                group: 2,
              },
              {
                bookId: "1KI",
                type: "complete",
                explodedViewPosition: { x: -0.35, y: -0.05, z: 0.51 },
                group: 2,
              },
              {
                bookId: "2SA",
                type: "complete",
                explodedViewPosition: { x: 0.35, y: 0.05, z: 0.61 },
                group: 1,
              },
              {
                bookId: "1SA",
                type: "complete",
                explodedViewPosition: { x: -0.35, y: -0.05, z: 0.63 },
                group: 1,
              },
              {
                bookId: "RUT",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.8 },
              },
              {
                bookId: "JDG",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.9 },
              },
              {
                bookId: "JOS",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 1 },
              },
            ],
          },
          {
            name: "Law",
            translationKey: "law",
            color: "#E5E67E",
            customExplodedViewScaleFactor: 2.5,
            books: [
              {
                bookId: "DEU",
                type: "complete",
                explodedViewPosition: { x: 0.4, y: 0.4, z: 0 },
              },
              {
                bookId: "NUM",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.25 },
              },
              {
                bookId: "LEV",
                type: "complete",
                explodedViewPosition: { x: -0.4, y: -0.4, z: 0.5 },
              },
              {
                bookId: "EXO",
                type: "complete",
                explodedViewPosition: { x: 0, y: 0, z: 0.75 },
              },
              {
                bookId: "GEN",
                type: "complete",
                explodedViewPosition: { x: 0.4, y: 0.4, z: 1 },
              },
            ],
          },
        ],
      },
    ],
  },
] as const;
