import { defineConfig } from "vite";
import preact from "@preact/preset-vite";
import path from "path";
import type { Plugin } from "vite";
import {
  VIRTUAL_ID,
  RESOLVED_ID,
  generateEntryModuleSource,
} from "../../script/lib/extensionsModule";

// The app's own `virtual:@extensions` module (script/lib/vite-plugin-extensions.ts)
// auto-discovers every extension package under the monorepo's `packages/`
// directory — a concept that doesn't exist once this package is built and
// consumed standalone. `SeedBibleStateManager.tsx` imports it as the default
// set of extensions to install, so the published build needs *some* module at
// that specifier; an empty extension set (generated by the exact same helper
// the real plugin uses) preserves that import without pulling the monorepo's
// directory layout into the bundle. Consumers that want default extensions
// install them explicitly through the public `ExtensionManager` API instead.
function emptyExtensionSetPlugin(): Plugin {
  return {
    name: "seed-bible-empty-extension-set",
    resolveId(id) {
      return id === VIRTUAL_ID ? RESOLVED_ID : null;
    },
    load(id) {
      return id === RESOLVED_ID
        ? generateEntryModuleSource([], "seed-bible")
        : null;
    },
  };
}

// A publishable library build: bundle only this package's own relative
// source, and leave every dependency (preact, rxjs, the @casual-simulation/*
// SDK, etc.) as an external import for the consumer's own node_modules to
// resolve — mirrors the root `vite.config.ts`'s app build in reusing the
// `preact()` plugin and `resolve.dedupe` list, but replaces its
// app-oriented `build` config with `build.lib`.
export default defineConfig({
  plugins: [preact(), emptyExtensionSetPlugin()],

  resolve: {
    // Same rationale as the root config: a second preact/signals instance
    // (e.g. pulled in transitively by a consumer's other dependencies) breaks
    // hooks. See that file's comment on `dedupe` for the full explanation.
    dedupe: [
      "preact",
      "preact/hooks",
      "preact/compat",
      "preact/jsx-runtime",
      "@preact/signals",
      "@preact/signals-core",
    ],
  },

  build: {
    outDir: "dist",
    // `tsconfig.build.json`'s `tsc --emitDeclarationOnly` writes the `.d.ts`
    // tree into this same `dist/`; emptying it here would delete that output
    // whenever this build step runs second. `pnpm run clean` (rimraf dist) is
    // what actually guarantees a fresh `dist/` between builds.
    emptyOutDir: false,
    sourcemap: true,
    lib: {
      entry: {
        api: path.resolve(__dirname, "seed-bible/app/api.tsx"),
        managers: path.resolve(__dirname, "seed-bible/managers/index.tsx"),
        components: path.resolve(__dirname, "seed-bible/components/index.tsx"),
        i18n: path.resolve(__dirname, "seed-bible/i18n/index.tsx"),
        styles: path.resolve(__dirname, "seed-bible/styles.ts"),
      },
      formats: ["es"],
      fileName: (_format, entryName) => `${entryName}.js`,
      // One merged `dist/style.css` instead of one per entry — the `styles`
      // entry above exists only to pull the foundation CSS into that same
      // file (see its own comment for why).
      cssFileName: "style",
    },
    cssCodeSplit: false,
    rollupOptions: {
      external: (id) =>
        !id.startsWith(".") && !path.isAbsolute(id) && id !== VIRTUAL_ID,
    },
  },
});
