import type { TabernacleScriptureDataPort } from "../../domain/ports/scriptureData";
import type { MeshState } from "../../domain/models/meshState";
import type {
  PieceChapterConfig,
  ScriptureVersesMap,
} from "../../domain/models/scripture";
import type { PieceKey, VerseReference } from "../../domain/models/piece";
import {
  getPieceStatesForChapter,
  getPiecesForVerse,
  getVersesForPiece,
} from "tabernacle.domain.functions.scripture";

// Chapter-by-chapter visibility config for each piece (ported from UpdateTabernacleVisuals.tsx)
const pieceChapterConfigs: PieceChapterConfig[] = [
  {
    key: "ark-of-covenant",
    chaptersInfo: {
      "25": "Shown",
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Shown",
      "37": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "incense-altar",
    chaptersInfo: {
      "30": "Shown",
      "37": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "menorah",
    chaptersInfo: {
      "25": "Shown",
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Shown",
      "37": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "table-of-showbread",
    chaptersInfo: {
      "25": "Shown",
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Shown",
      "37": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "inner-curtain",
    chaptersInfo: {
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Translucent",
      "36": "Shown",
      "37": "Translucent",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "front-curtain",
    chaptersInfo: {
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Translucent",
      "36": "Shown",
      "37": "Translucent",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "front-pillars",
    chaptersInfo: {
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Hidden",
      "36": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "inner-pillars",
    chaptersInfo: {
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Hidden",
      "36": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "walls",
    chaptersInfo: {
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Hidden",
      "36": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "bars",
    chaptersInfo: {
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Hidden",
      "36": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "rings",
    chaptersInfo: {
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Hidden",
      "36": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "altar-of-sacrifice",
    chaptersInfo: {
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "bronze-laver",
    chaptersInfo: {
      "30": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "purple-curtain",
    chaptersInfo: {
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Hidden",
      "36": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "brown-curtain",
    chaptersInfo: {
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Hidden",
      "36": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "red-curtain",
    chaptersInfo: {
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Hidden",
      "36": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "grey-curtain",
    chaptersInfo: {
      "26": "Shown",
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Hidden",
      "36": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "ground",
    chaptersInfo: {
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
  {
    key: "fence",
    chaptersInfo: {
      "27": "Shown",
      "28": "Shown",
      "29": "Shown",
      "30": "Shown",
      "38": "Shown",
      "39": "Shown",
      "40": "Shown",
    },
  },
];

// Scripture verse data: EXO → chapter → verse → piece keys
const scriptureVersesData: ScriptureVersesMap = {
  EXO: {
    "25": {
      "9": ["tabernacle"],
      "10": ["ark-of-covenant"],
      "11": ["ark-of-covenant"],
      "12": ["ark-of-covenant"],
      "13": ["ark-of-covenant"],
      "14": ["ark-of-covenant"],
      "15": ["ark-of-covenant"],
      "16": ["ark-of-covenant"],
      "17": ["ark-of-covenant"],
      "18": ["ark-of-covenant"],
      "19": ["ark-of-covenant"],
      "20": ["ark-of-covenant"],
      "21": ["ark-of-covenant"],
      "22": ["ark-of-covenant"],
      "23": ["table-of-showbread"],
      "24": ["table-of-showbread"],
      "25": ["table-of-showbread"],
      "26": ["table-of-showbread"],
      "27": ["table-of-showbread"],
      "28": ["table-of-showbread"],
      "29": ["table-of-showbread"],
      "30": ["table-of-showbread"],
      "31": ["menorah"],
      "32": ["menorah"],
      "33": ["menorah"],
      "34": ["menorah"],
      "35": ["menorah"],
      "36": ["menorah"],
      "37": ["menorah"],
      "38": ["menorah"],
      "39": ["menorah"],
      "40": ["menorah"],
    },
    "26": {
      "1": ["inner-curtain"],
      "2": ["inner-curtain"],
      "3": ["inner-curtain"],
      "4": ["inner-curtain"],
      "5": ["inner-curtain"],
      "6": ["inner-curtain"],
      "7": ["brown-curtain"],
      "8": ["brown-curtain"],
      "9": ["brown-curtain"],
      "10": ["brown-curtain"],
      "11": ["brown-curtain"],
      "12": ["brown-curtain"],
      "13": ["brown-curtain"],
      "14": ["red-curtain"],
      "15": ["walls"],
      "16": ["walls"],
      "17": ["walls"],
      "18": ["walls"],
      "19": ["walls"],
      "20": ["walls"],
      "21": ["walls"],
      "22": ["walls"],
      "23": ["walls"],
      "24": ["walls"],
      "25": ["walls"],
      "26": ["bars"],
      "27": ["bars"],
      "28": ["bars"],
      "29": ["bars"],
      "31": ["inner-curtain"],
      "32": ["inner-pillars"],
      "33": ["inner-curtain"],
      "34": ["ark-of-covenant"],
      "35": ["table-of-showbread", "menorah"],
      "36": ["front-curtain"],
      "37": ["front-pillars"],
    },
    "27": {
      "1": ["altar-of-sacrifice"],
      "2": ["altar-of-sacrifice"],
      "3": ["altar-of-sacrifice"],
      "4": ["altar-of-sacrifice"],
      "5": ["altar-of-sacrifice"],
      "6": ["altar-of-sacrifice"],
      "7": ["altar-of-sacrifice"],
      "8": ["altar-of-sacrifice"],
      "9": ["fence"],
      "10": ["fence"],
      "11": ["fence"],
      "12": ["fence"],
      "13": ["fence"],
      "14": ["fence"],
      "15": ["fence"],
      "16": ["fence"],
      "17": ["fence"],
      "18": ["fence"],
      "20": ["menorah"],
      "21": ["menorah"],
    },
    "28": {},
    "29": {
      "12": ["altar-of-sacrifice"],
      "16": ["altar-of-sacrifice"],
      "20": ["altar-of-sacrifice"],
      "21": ["altar-of-sacrifice"],
      "37": ["altar-of-sacrifice"],
    },
    "30": {
      "1": ["incense-altar"],
      "2": ["incense-altar"],
      "3": ["incense-altar"],
      "4": ["incense-altar"],
      "5": ["incense-altar"],
      "6": ["incense-altar"],
      "7": ["incense-altar"],
      "8": ["incense-altar"],
      "9": ["incense-altar"],
      "10": ["incense-altar"],
      "17": ["bronze-laver"],
      "18": ["bronze-laver"],
      "19": ["bronze-laver"],
      "20": ["bronze-laver"],
      "21": ["bronze-laver"],
      "26": ["ark-of-covenant", "table-of-showbread", "menorah"],
      "27": ["incense-altar"],
      "28": ["altar-of-sacrifice"],
    },
    "36": {
      "8": ["inner-curtain"],
      "9": ["inner-curtain"],
      "10": ["inner-curtain"],
      "11": ["inner-curtain"],
      "12": ["inner-curtain"],
      "13": ["inner-curtain"],
      "14": ["brown-curtain"],
      "15": ["brown-curtain"],
      "16": ["brown-curtain"],
      "17": ["brown-curtain"],
      "18": ["brown-curtain"],
      "19": ["red-curtain"],
      "20": ["walls"],
      "21": ["walls"],
      "22": ["walls"],
      "23": ["walls"],
      "24": ["walls"],
      "25": ["walls"],
      "26": ["walls"],
      "27": ["walls"],
      "28": ["walls"],
      "29": ["walls"],
      "30": ["walls"],
      "31": ["bars"],
      "32": ["bars"],
      "33": ["bars"],
      "34": ["bars"],
      "35": ["inner-curtain"],
      "36": ["inner-pillars"],
      "37": ["front-curtain"],
      "38": ["front-pillars"],
    },
    "37": {
      "1": ["ark-of-covenant"],
      "2": ["ark-of-covenant"],
      "3": ["ark-of-covenant"],
      "4": ["ark-of-covenant"],
      "5": ["ark-of-covenant"],
      "6": ["ark-of-covenant"],
      "7": ["ark-of-covenant"],
      "8": ["ark-of-covenant"],
      "9": ["ark-of-covenant"],
      "10": ["table-of-showbread"],
      "11": ["table-of-showbread"],
      "12": ["table-of-showbread"],
      "13": ["table-of-showbread"],
      "14": ["table-of-showbread"],
      "15": ["table-of-showbread"],
      "16": ["table-of-showbread"],
      "17": ["menorah"],
      "18": ["menorah"],
      "19": ["menorah"],
      "20": ["menorah"],
      "21": ["menorah"],
      "22": ["menorah"],
      "23": ["menorah"],
      "24": ["menorah"],
      "25": ["incense-altar"],
      "26": ["incense-altar"],
      "27": ["incense-altar"],
      "28": ["incense-altar"],
      "29": ["incense-altar"],
    },
    "38": {
      "1": ["altar-of-sacrifice"],
      "2": ["altar-of-sacrifice"],
      "3": ["altar-of-sacrifice"],
      "4": ["altar-of-sacrifice"],
      "5": ["altar-of-sacrifice"],
      "6": ["altar-of-sacrifice"],
      "7": ["altar-of-sacrifice"],
      "8": ["bronze-laver"],
      "9": ["fence"],
      "10": ["fence"],
      "11": ["fence"],
      "12": ["fence"],
      "13": ["fence"],
      "14": ["fence"],
      "15": ["fence"],
      "16": ["fence"],
      "17": ["fence"],
      "18": ["fence"],
    },
    "39": {
      "32": ["tabernacle"],
      "33": [
        "tabernacle",
        "ark-of-covenant",
        "table-of-showbread",
        "menorah",
        "incense-altar",
        "altar-of-sacrifice",
        "bronze-laver",
      ],
      "34": ["inner-curtain", "front-curtain"],
      "35": ["ark-of-covenant"],
      "36": ["table-of-showbread"],
      "37": ["menorah"],
      "38": ["incense-altar", "altar-of-sacrifice", "bronze-laver"],
      "39": ["fence"],
      "40": ["tabernacle"],
    },
    "40": {
      "2": ["tabernacle"],
      "3": ["ark-of-covenant"],
      "5": ["incense-altar"],
      "6": ["altar-of-sacrifice"],
      "7": ["bronze-laver"],
      "17": ["tabernacle"],
      "18": ["tabernacle"],
      "19": ["ark-of-covenant"],
      "20": ["ark-of-covenant"],
      "21": ["inner-curtain", "ark-of-covenant"],
      "22": ["table-of-showbread"],
      "24": ["menorah"],
      "26": ["incense-altar"],
      "28": ["front-curtain"],
      "29": ["altar-of-sacrifice"],
      "30": ["bronze-laver"],
      "33": ["fence", "front-curtain"],
    },
  },
};

export class ScriptureDataConfigProvider implements TabernacleScriptureDataPort {
  getPieceStatesForChapter(
    bookId: string,
    chapter: number
  ): Map<PieceKey, MeshState> {
    return getPieceStatesForChapter(pieceChapterConfigs, bookId, chapter);
  }

  getPiecesForVerse(
    bookId: string,
    chapter: number,
    verse: number
  ): PieceKey[] {
    return getPiecesForVerse(scriptureVersesData, bookId, chapter, verse);
  }

  getVersesForPiece(
    key: PieceKey,
    currentBookId: string,
    currentChapter: number
  ): { inChapter: VerseReference[]; inOtherChapters: VerseReference[] } {
    return getVersesForPiece(
      scriptureVersesData,
      key,
      currentBookId,
      currentChapter
    );
  }
}
