import { BiblePieces } from "../../../domain/models/canvas";
import type { BotTypeMap } from "../../models/stack";

export const INITIAL_CONFIG_MAP: {
  [K in keyof BotTypeMap]: Partial<BotTypeMap[K]["tags"]>;
} = {
  [BiblePieces.StackTestament]: {
    draggable: false,
    formOpacity: 1,
    scale: 1,
    color: "#ffffff",
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    pointable: false,
    system: undefined,
    cursor: "pointer",
    formAddress:
      "https://auth-aux-aobot-prod-filesbucket-141297942820.s3.amazonaws.com/Sandbox/5686459242af8261bbab101a8d2c7ceaab6ef8ffcf0f96fe62c622d0322c6c30.webp",
    strokeWidth: 1,
  },
  [BiblePieces.StackSection]: {
    draggable: false,
    formOpacity: 0.7,
    scale: 1,
    color: "#ffffff",
    strokeColor: "#ffffff",
    labelOpacity: 1,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    system: undefined,
    cursor: "pointer",
    formAddress:
      "https://auth-aux-aobot-prod-filesbucket-141297942820.s3.amazonaws.com/Sandbox/5686459242af8261bbab101a8d2c7ceaab6ef8ffcf0f96fe62c622d0322c6c30.webp",
    strokeWidth: 1,
  },
  [BiblePieces.StackBook]: {
    draggable: false,
    formOpacity: 0,
    color: "#ffffff",
    strokeColor: "#ffffff",
    labelOpacity: 1,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    system: undefined,
    cursor: "pointer",
    formAddress:
      "https://auth-aux-aobot-prod-filesbucket-141297942820.s3.amazonaws.com/Sandbox/5686459242af8261bbab101a8d2c7ceaab6ef8ffcf0f96fe62c622d0322c6c30.webp",
    strokeWidth: 2,
  },
  [BiblePieces.StackSectionBook]: {
    draggable: false,
    formOpacity: 0,
    color: "#ffffff",
    strokeColor: "#ffffff",
    labelOpacity: 1,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    system: undefined,
    cursor: "pointer",
    formAddress:
      "https://auth-aux-aobot-prod-filesbucket-141297942820.s3.amazonaws.com/Sandbox/5686459242af8261bbab101a8d2c7ceaab6ef8ffcf0f96fe62c622d0322c6c30.webp",
    strokeWidth: 2,
  },
  [BiblePieces.StackChapter]: {
    draggable: true,
    pointable: true,
    color: "#e8e8e8",
    label: "1",
    labelPosition: "front",
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    system: undefined,
    cursor: "pointer",
  },
  [BiblePieces.StackSectionShadow]: {
    draggable: false,
    pointable: false,
    formOpacity: 0,
    color: undefined,
    scaleX: undefined,
    scaleY: undefined,
    scaleZ: undefined,
    sectionName: undefined,
    sectionDataId: undefined,
    system: undefined,
    cursor: "pointer",
    formDepthTest: false,
  },
  [BiblePieces.VersesBundle]: {
    color: "#d3d3d3",
    labelOpacity: 1,
    scaleX: 3.5,
    scaleY: 1,
    scaleZ: 0,
    label: undefined,
    draggable: undefined,
    system: undefined,
    cursor: "pointer",
  },
  [BiblePieces.Verse]: {
    scaleZ: 1,
    system: undefined,
    color: "#c1c1c1",
    cursor: "pointer",
    labelPosition: "top",
  },
  [BiblePieces.StackCover]: {
    draggable: false,
    color: "black",
    pointable: undefined,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    stackBibleId: undefined,
    system: undefined,
    scale: 1,
    cursor: "pointer",
    formOpacity: 1,
    labelSize: 1,
  },
  [BiblePieces.StackCrossLine]: {
    draggable: false,
    color: "#FFD700",
    pointable: false,
    formOpacity: 1,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.05,
    stackBibleId: undefined,
    system: undefined,
    cursor: "pointer",
  },
  [BiblePieces.StackTransformer]: {
    draggable: false,
    pointable: false,
    color: "clear",
    toErase: true,
    stackBibleId: undefined,
    system: undefined,
    scale: 1,
    scaleZ: 1,
  },
  [BiblePieces.StackShadow]: {
    draggable: false,
    pointable: false,
    color: "#7B64FF",
    stackBibleId: undefined,
    system: undefined,
    form: "sprite",
    formAddress:
      "https://publicos-link-filesbucket-404655125928.s3.amazonaws.com/ab-1/e58dd8fde3202f0ec0f3cfb1f87b1cf516c195202e67d618a8a88c7384d674de.png",
    formOpacity: 0.3,
    scaleX: 6,
    scaleY: 6,
  },
  // Pieces without an initial pool configuration (not part of poolsData).
  [BiblePieces.ActivityIndicator]: {},
  [BiblePieces.ActivityNotification]: {},
  [BiblePieces.InfoLabelDate]: {},
  [BiblePieces.InfoLabelTail]: {},
  [BiblePieces.InfoLabelText]: {},
  [BiblePieces.InfoLabelTransformer]: {},
} as const;
