export const BookNames = {
  Acts: "Acts",
  Amos: "Amos",
  Colossians: "Colossians",
  Daniel: "Daniel",
  Deuteronomy: "Deuteronomy",
  Ecclesiastes: "Ecclesiastes",
  Ephesians: "Ephesians",
  Esther: "Esther",
  Exodus: "Exodus",
  Ezekiel: "Ezekiel",
  Ezra: "Ezra",
  "1 Chronicles": "1 Chronicles",
  "1 Corinthians": "1 Corinthians",
  "1 John": "1 John",
  "1 Kings": "1 Kings",
  "1 Peter": "1 Peter",
  "1 Samuel": "1 Samuel",
  "1 Thessalonians": "1 Thessalonians",
  "1 Timothy": "1 Timothy",
  "1 Psalms": "1 Psalms",
  "2 Psalms": "2 Psalms",
  "3 Psalms": "3 Psalms",
  "4 Psalms": "4 Psalms",
  "5 Psalms": "5 Psalms",
  Galatians: "Galatians",
  Genesis: "Genesis",
  Habakkuk: "Habakkuk",
  Haggai: "Haggai",
  Hebrews: "Hebrews",
  Hosea: "Hosea",
  Isaiah: "Isaiah",
  James: "James",
  Jeremiah: "Jeremiah",
  Job: "Job",
  Joel: "Joel",
  John: "John",
  Jonah: "Jonah",
  Joshua: "Joshua",
  Jude: "Jude",
  Judges: "Judges",
  Lamentations: "Lamentations",
  Leviticus: "Leviticus",
  Luke: "Luke",
  Malachi: "Malachi",
  Mark: "Mark",
  Matthew: "Matthew",
  Micah: "Micah",
  Nahum: "Nahum",
  Nehemiah: "Nehemiah",
  Numbers: "Numbers",
  Obadiah: "Obadiah",
  Philemon: "Philemon",
  Philippians: "Philippians",
  Proverbs: "Proverbs",
  Revelation: "Revelation",
  Romans: "Romans",
  Ruth: "Ruth",
  "2 Chronicles": "2 Chronicles",
  "2 Corinthians": "2 Corinthians",
  "2 John": "2 John",
  "2 Kings": "2 Kings",
  "2 Peter": "2 Peter",
  "2 Samuel": "2 Samuel",
  "2 Thessalonians": "2 Thessalonians",
  "2 Timothy": "2 Timothy",
  "Song of Songs": "Song of Songs",
  "3 John": "3 John",
  Titus: "Titus",
  Zechariah: "Zechariah",
  Zephaniah: "Zephaniah",
} as const;

export type BookName = (typeof BookNames)[keyof typeof BookNames];
