import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { Project } from "ts-morph";

type CheckError = {
  filePath: string;
  line: number;
  column: number;
  code: number;
};

const OUTPUT_DIRECTORY = path.resolve("typings");
const OUTPUT_FILE_PREFIX = "autogenerated_globals_";
const OUTPUT_FILE_SUFFIX = ".d.ts";
const TARGET_ERROR_CODE = 7017;

function findGlobalThisErrorsFromTsMorph(): CheckError[] {
  const project = new Project({
    tsConfigFilePath: path.resolve("tsconfig.json"),
  });

  const diagnostics = project.getPreEmitDiagnostics();
  const errors: CheckError[] = [];

  for (const diagnostic of diagnostics) {
    if (diagnostic.getCode() !== TARGET_ERROR_CODE) {
      continue;
    }

    const sourceFile = diagnostic.getSourceFile();
    const start = diagnostic.getStart();
    if (!sourceFile || start == null) {
      continue;
    }

    const lineAndColumn = sourceFile.getLineAndColumnAtPos(start);
    errors.push({
      filePath: sourceFile.getFilePath(),
      line: lineAndColumn.line,
      column: lineAndColumn.column,
      code: TARGET_ERROR_CODE,
    });
  }

  return errors;
}

function getGlobalAliases(fileContent: string): Set<string> {
  const aliases = new Set<string>(["globalThis"]);
  const aliasRegex =
    /\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*globalThis\b/g;
  let match: RegExpExecArray | null;

  while ((match = aliasRegex.exec(fileContent)) !== null) {
    const alias = match[1];
    if (alias) {
      aliases.add(alias);
    }
  }

  return aliases;
}

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function getIdentifierNearColumn(
  lineText: string,
  column: number
): string | null {
  if (!lineText) {
    return null;
  }

  const index = Math.max(0, column - 1);

  const identifierRegex = /[A-Za-z_$][\w$]*/g;
  let match: RegExpExecArray | null;
  while ((match = identifierRegex.exec(lineText)) !== null) {
    const value = match[0];
    const start = match.index;
    const end = start + value.length;
    if (index >= start && index <= end) {
      return value;
    }
  }

  return null;
}

function extractGlobalsFromLine(
  lineText: string,
  aliases: Set<string>,
  column: number
): Set<string> {
  const candidates = new Set<string>();

  for (const alias of aliases) {
    const safeAlias = escapeRegExp(alias);

    const dotAccessRegex = new RegExp(
      `\\b${safeAlias}(?:\\?\\.)?\\.([A-Za-z_$][\\w$]*)`,
      "g"
    );
    let dotMatch: RegExpExecArray | null;
    while ((dotMatch = dotAccessRegex.exec(lineText)) !== null) {
      if (dotMatch[1]) {
        candidates.add(dotMatch[1]);
      }
    }

    const bracketAccessRegex = new RegExp(
      `\\b${safeAlias}\\[(?:"([A-Za-z_$][\\w$]*)"|'([A-Za-z_$][\\w$]*)'|\`([A-Za-z_$][\\w$]*)\`)\\]`,
      "g"
    );
    let bracketMatch: RegExpExecArray | null;
    while ((bracketMatch = bracketAccessRegex.exec(lineText)) !== null) {
      const globalName = bracketMatch[1] || bracketMatch[2] || bracketMatch[3];
      if (globalName) {
        candidates.add(globalName);
      }
    }
  }

  if (candidates.size === 0) {
    const nearIdentifier = getIdentifierNearColumn(lineText, column);
    if (nearIdentifier) {
      candidates.add(nearIdentifier);
    }
  }

  return candidates;
}

function getSourceLine(fileContent: string, line: number): string {
  const lines = fileContent.split(/\r?\n/);
  return lines[line - 1] ?? "";
}

function normalizePath(filePath: string): string {
  const trimmed = filePath.trim();
  if (path.isAbsolute(trimmed)) {
    return trimmed;
  }
  return path.resolve(trimmed);
}

function buildDts(globals: string[]): string {
  const sorted = [...globals].sort((a, b) => a.localeCompare(b));

  const lines = [
    "// This file is auto-generated by script/generateGlobalTypes.ts",
    "// Do not edit manually.",
    "",
    "export {};",
    "",
    "declare global {",
    ...sorted.map((name) => `  var ${name}: any;`),
    "}",
    "",
  ];

  return lines.join("\n");
}

async function getNextOutputFilePath(): Promise<string> {
  const files = await readdir(OUTPUT_DIRECTORY, { withFileTypes: true });
  let maxIndex = 0;

  for (const file of files) {
    if (!file.isFile()) {
      continue;
    }

    const match = file.name.match(/^autogenerated_globals_(\d+)\.d\.ts$/);
    if (!match) {
      continue;
    }

    const index = Number(match[1]);
    if (!Number.isNaN(index)) {
      maxIndex = Math.max(maxIndex, index);
    }
  }

  const nextIndex = maxIndex + 1;
  const fileName = `${OUTPUT_FILE_PREFIX}${nextIndex}${OUTPUT_FILE_SUFFIX}`;
  return path.resolve(OUTPUT_DIRECTORY, fileName);
}

async function generateGlobalTypes() {
  const outputFilePath = await getNextOutputFilePath();
  const errors = findGlobalThisErrorsFromTsMorph();

  const globals = new Set<string>();
  const fileCache = new Map<string, string>();

  for (const error of errors) {
    const absolutePath = normalizePath(error.filePath);

    let fileContent = fileCache.get(absolutePath);
    if (!fileContent) {
      try {
        fileContent = await readFile(absolutePath, "utf8");
      } catch {
        continue;
      }
      fileCache.set(absolutePath, fileContent);
    }

    const aliases = getGlobalAliases(fileContent);
    const sourceLine = getSourceLine(fileContent, error.line);
    const found = extractGlobalsFromLine(sourceLine, aliases, error.column);

    for (const globalName of found) {
      globals.add(globalName);
    }
  }

  if (globals.size > 0) {
    await writeFile(outputFilePath, buildDts([...globals]), "utf8");

    console.log(
      `Generated ${path.relative(process.cwd(), outputFilePath)} with ${globals.size} globals from TS${TARGET_ERROR_CODE} errors.`
    );
  } else {
    console.log(
      `No TS${TARGET_ERROR_CODE} errors found. No global types generated.`
    );
  }
}

await generateGlobalTypes();
