import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { Project, SyntaxKind, VariableDeclaration } from "ts-morph";

type LocationMetadata = {
  filePath: string;
  lineNumber: number;
  columnNumber: number;
};

type TypeMetadata = {
  text: string;
  name: string;
  genericTypeParameters?: string[];
};

type UsageMetadata = {
  location: LocationMetadata;
  kind: string;
  type?: TypeMetadata;
  argumentTypes?: TypeMetadata[];
  propertyName?: string;
  loopRole?: string;
};

type GlobalUsageMetadata = {
  definitionLocation: LocationMetadata;
  name: string;
  usages: UsageMetadata[];
};

type UsageReport = {
  generatedAt: string;
  outputVersion: string;
  sourceFiles: string[];
  globals: GlobalUsageMetadata[];
};

type Recommendation = {
  name: string;
  definitionLocation: LocationMetadata;
  currentType: string;
  recommendedType: string;
  reason: string;
};

type RecommendationReport = {
  generatedAt: string;
  inputMapPath: string;
  updatedDeclarations: number;
  skippedDeclarations: number;
  recommendations: Recommendation[];
};

const USAGE_MAP_PATH = path.resolve(
  "typings",
  "autogenerated_globals_any_usage_map.json"
);
const RECOMMENDATION_REPORT_PATH = path.resolve(
  "typings",
  "autogenerated_globals_type_recommendations.json"
);

function resolveWorkspacePath(relativePath: string): string {
  return path.resolve(relativePath);
}

function normalizeTypeText(typeText: string): string {
  const trimmed = typeText.trim();
  if (!trimmed) {
    return "";
  }

  if (/^\d+(?:\.\d+)?$/.test(trimmed)) {
    return "number";
  }

  if (
    /^".*"$/.test(trimmed) ||
    /^'.*'$/.test(trimmed) ||
    /^`.*`$/.test(trimmed)
  ) {
    return "string";
  }

  if (trimmed === "true" || trimmed === "false") {
    return "boolean";
  }

  if (trimmed === "null") {
    return "null";
  }

  if (trimmed === "undefined") {
    return "undefined";
  }

  return trimmed;
}

function isUsefulType(typeText: string): boolean {
  const normalized = normalizeTypeText(typeText);
  if (!normalized) {
    return false;
  }

  const blocked = new Set(["any", "unknown", "never"]);
  if (blocked.has(normalized)) {
    return false;
  }

  return true;
}

function scoreUsageKind(kind: string): number {
  switch (kind) {
    case "assignment":
      return 10;
    case "variable-initializer":
      return 9;
    case "function-call":
      return 8;
    case "function-argument":
      return 6;
    case "method-call":
      return 5;
    case "property-access":
      return 4;
    case "element-access":
      return 4;
    case "for-of-loop":
    case "for-in-loop":
      return 3;
    case "for-loop":
      return 2;
    default:
      return 1;
  }
}

function inferFunctionTypeFromCalls(usages: UsageMetadata[]): string | null {
  const callUsages = usages.filter((usage) => usage.kind === "function-call");
  if (callUsages.length === 0) {
    return null;
  }

  const signatures = new Set<string>();

  for (const usage of callUsages) {
    const args = usage.argumentTypes ?? [];
    const params = args.map((arg, index) => {
      const typeText = isUsefulType(arg.text)
        ? normalizeTypeText(arg.text)
        : "any";
      return `arg${index}: ${typeText}`;
    });

    signatures.add(`(${params.join(", ")}) => any`);
  }

  if (signatures.size === 0) {
    return null;
  }

  if (signatures.size === 1) {
    return [...signatures][0];
  }

  return [...signatures].sort((a, b) => a.localeCompare(b)).join(" | ");
}

function inferBestType(globalEntry: GlobalUsageMetadata): {
  recommendedType: string | null;
  reason: string;
} {
  const scoreByType = new Map<string, number>();

  for (const usage of globalEntry.usages) {
    if (!usage.type?.text) {
      continue;
    }

    if (!isUsefulType(usage.type.text)) {
      continue;
    }

    const normalizedType = normalizeTypeText(usage.type.text);
    const prevScore = scoreByType.get(normalizedType) ?? 0;
    scoreByType.set(normalizedType, prevScore + scoreUsageKind(usage.kind));
  }

  const functionType = inferFunctionTypeFromCalls(globalEntry.usages);
  if (functionType) {
    const prevScore = scoreByType.get(functionType) ?? 0;
    scoreByType.set(functionType, prevScore + 7);
  }

  if (scoreByType.size === 0) {
    return {
      recommendedType: null,
      reason: "No non-any usage types were available.",
    };
  }

  const ranked = [...scoreByType.entries()].sort((a, b) => {
    if (a[1] !== b[1]) {
      return b[1] - a[1];
    }

    if (a[0] === "string" || a[0] === "number" || a[0] === "boolean") {
      return -1;
    }
    if (b[0] === "string" || b[0] === "number" || b[0] === "boolean") {
      return 1;
    }

    return a[0].localeCompare(b[0]);
  });

  const [bestType, bestScore] = ranked[0];
  const second = ranked[1];

  if (second && second[1] === bestScore && second[0] !== bestType) {
    return {
      recommendedType: `${bestType} | ${second[0]}`,
      reason: `Top evidence tied between ${bestType} and ${second[0]}.`,
    };
  }

  return {
    recommendedType: bestType,
    reason: `Selected by strongest usage evidence score (${bestScore}).`,
  };
}

function findDeclarationAtLocation(
  declarations: VariableDeclaration[],
  expectedName: string,
  lineNumber: number
): VariableDeclaration | undefined {
  return declarations.find((declaration) => {
    if (declaration.getName() !== expectedName) {
      return false;
    }

    const line = declaration
      .getSourceFile()
      .getLineAndColumnAtPos(declaration.getNameNode().getStart()).line;

    return line === lineNumber;
  });
}

async function inferGlobalTypesFromUsage() {
  const mapText = await readFile(USAGE_MAP_PATH, "utf8");
  const usageReport = JSON.parse(mapText) as UsageReport;

  const project = new Project({
    tsConfigFilePath: path.resolve("tsconfig.json"),
  });

  const recommendations: Recommendation[] = [];
  let updatedDeclarations = 0;
  let skippedDeclarations = 0;

  for (const globalEntry of usageReport.globals) {
    const inference = inferBestType(globalEntry);
    if (!inference.recommendedType) {
      skippedDeclarations += 1;
      continue;
    }

    const definitionPath = resolveWorkspacePath(
      globalEntry.definitionLocation.filePath
    );
    const sourceFile = project.getSourceFile(definitionPath);

    if (!sourceFile) {
      skippedDeclarations += 1;
      continue;
    }

    const declarations = sourceFile.getDescendantsOfKind(
      SyntaxKind.VariableDeclaration
    );
    const declaration = findDeclarationAtLocation(
      declarations,
      globalEntry.name,
      globalEntry.definitionLocation.lineNumber
    );

    if (!declaration) {
      skippedDeclarations += 1;
      continue;
    }

    const currentType =
      declaration.getTypeNode()?.getText()?.trim() ??
      declaration.getType().getText();
    if (currentType === inference.recommendedType) {
      skippedDeclarations += 1;
      continue;
    }

    declaration.setType(inference.recommendedType);
    updatedDeclarations += 1;

    recommendations.push({
      name: globalEntry.name,
      definitionLocation: globalEntry.definitionLocation,
      currentType,
      recommendedType: inference.recommendedType,
      reason: inference.reason,
    });
  }

  await project.save();

  const report: RecommendationReport = {
    generatedAt: new Date().toISOString(),
    inputMapPath: path
      .relative(process.cwd(), USAGE_MAP_PATH)
      .replace(/\\/g, "/"),
    updatedDeclarations,
    skippedDeclarations,
    recommendations: recommendations.sort((a, b) =>
      a.name.localeCompare(b.name)
    ),
  };

  await writeFile(
    RECOMMENDATION_REPORT_PATH,
    `${JSON.stringify(report, null, 2)}\n`,
    "utf8"
  );

  console.log(
    `Updated ${updatedDeclarations} global declarations and wrote ${path
      .relative(process.cwd(), RECOMMENDATION_REPORT_PATH)
      .replace(/\\/g, "/")}.`
  );
}

await inferGlobalTypesFromUsage();
