import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { Project, SyntaxKind, VariableDeclaration } from "ts-morph";

type LocationMetadata = {
  filePath: string;
  lineNumber: number;
  columnNumber: number;
};

type TypeMetadata = {
  text: string;
  name: string;
  genericTypeParameters?: string[];
};

type UsageMetadata = {
  location: LocationMetadata;
  kind: string;
  type?: TypeMetadata;
  argumentTypes?: TypeMetadata[];
  argumentNames?: string[];
  propertyName?: string;
  loopRole?: string;
};

type GlobalUsageMetadata = {
  definitionLocation: LocationMetadata;
  name: string;
  usages: UsageMetadata[];
};

type UsageReport = {
  generatedAt: string;
  outputVersion: string;
  sourceFiles: string[];
  globals: GlobalUsageMetadata[];
};

type Recommendation = {
  name: string;
  definitionLocation: LocationMetadata;
  currentType: string;
  recommendedType: string;
  reason: string;
};

type RecommendationReport = {
  generatedAt: string;
  inputMapPath: string;
  updatedDeclarations: number;
  skippedDeclarations: number;
  recommendations: Recommendation[];
};

type FunctionInference = {
  typeText: string;
  score: number;
};

const USAGE_MAP_PATH = path.resolve(
  "typings",
  "autogenerated_globals_any_usage_map.json"
);
const RECOMMENDATION_REPORT_PATH = path.resolve(
  "typings",
  "autogenerated_globals_type_recommendations.json"
);

function resolveWorkspacePath(relativePath: string): string {
  return path.resolve(relativePath);
}

function normalizeTypeText(typeText: string): string {
  const trimmed = typeText.trim();
  if (!trimmed) {
    return "";
  }

  if (/^\d+(?:\.\d+)?$/.test(trimmed)) {
    return "number";
  }

  if (
    /^".*"$/.test(trimmed) ||
    /^'.*'$/.test(trimmed) ||
    /^`.*`$/.test(trimmed)
  ) {
    return "string";
  }

  if (trimmed === "true" || trimmed === "false") {
    return "boolean";
  }

  if (trimmed === "null") {
    return "null";
  }

  if (trimmed === "undefined") {
    return "undefined";
  }

  return trimmed;
}

function isUsefulType(typeText: string): boolean {
  const normalized = normalizeTypeText(typeText);
  if (!normalized) {
    return false;
  }

  const blocked = new Set(["any", "unknown", "never"]);
  if (blocked.has(normalized)) {
    return false;
  }

  return true;
}

function containsAnyKeyword(typeText: string): boolean {
  return /\bany\b/.test(typeText);
}

function normalizeParameterName(name: string, fallbackIndex: number): string {
  const cleaned = name
    .trim()
    .replace(/^[^A-Za-z_$]+/, "")
    .replace(/[^\w$]/g, "_")
    .replace(/_+/g, "_");

  if (!cleaned || !/^[A-Za-z_$][\w$]*$/.test(cleaned)) {
    return `arg${fallbackIndex}`;
  }

  return cleaned;
}

function getPreferredArgumentNames(usages: UsageMetadata[]): string[] {
  const countsByIndex = new Map<number, Map<string, number>>();

  for (const usage of usages) {
    if (usage.kind !== "function-call") {
      continue;
    }

    const names = usage.argumentNames ?? [];
    for (let index = 0; index < names.length; index += 1) {
      const normalized = normalizeParameterName(names[index] ?? "", index);
      if (normalized === `arg${index}`) {
        continue;
      }

      let bucket = countsByIndex.get(index);
      if (!bucket) {
        bucket = new Map<string, number>();
        countsByIndex.set(index, bucket);
      }

      bucket.set(normalized, (bucket.get(normalized) ?? 0) + 1);
    }
  }

  const result: string[] = [];
  for (const [index, bucket] of [...countsByIndex.entries()].sort(
    (a, b) => a[0] - b[0]
  )) {
    const ranked = [...bucket.entries()].sort((a, b) => {
      if (a[1] !== b[1]) {
        return b[1] - a[1];
      }
      return a[0].localeCompare(b[0]);
    });

    const topName = ranked[0]?.[0];
    result[index] = topName ?? `arg${index}`;
  }

  return result;
}

function applyPreferredArgumentNames(
  typeText: string,
  preferredNames: string[]
): string {
  if (!typeText.includes("=>") || preferredNames.length === 0) {
    return typeText;
  }

  const usedNames = new Set<string>();
  const finalNames = preferredNames.map((name, index) => {
    const base = normalizeParameterName(name, index);
    if (!usedNames.has(base)) {
      usedNames.add(base);
      return base;
    }

    let suffix = 2;
    while (usedNames.has(`${base}${suffix}`)) {
      suffix += 1;
    }

    const unique = `${base}${suffix}`;
    usedNames.add(unique);
    return unique;
  });

  return typeText.replace(/\barg(\d+)\b/g, (full, rawIndex: string) => {
    const index = Number(rawIndex);
    if (Number.isNaN(index)) {
      return full;
    }

    return finalNames[index] ?? full;
  });
}

function specificityBonus(typeText: string): number {
  if (containsAnyKeyword(typeText)) {
    return -8;
  }

  if (typeText === "null" || typeText === "undefined") {
    return -3;
  }

  if (typeText.includes("=>")) {
    return 3;
  }

  if (typeText.startsWith("{")) {
    return 2;
  }

  return 0;
}

function scoreUsageKind(kind: string): number {
  switch (kind) {
    case "assignment":
      return 10;
    case "variable-initializer":
      return 9;
    case "function-call":
      return 8;
    case "function-argument":
      return 6;
    case "method-call":
      return 5;
    case "property-access":
      return 4;
    case "element-access":
      return 4;
    case "for-of-loop":
    case "for-in-loop":
      return 3;
    case "for-loop":
      return 2;
    default:
      return 1;
  }
}

function formatUnionTypeParts(typeParts: string[]): string {
  const normalized = [
    ...new Set(typeParts.map((part) => part.trim()).filter(Boolean)),
  ];
  return normalized
    .map((part) => {
      if (/^\(.*\)$/.test(part)) {
        return part;
      }
      return `(${part})`;
    })
    .join(" | ");
}

function inferFunctionTypeFromCalls(
  usages: UsageMetadata[]
): FunctionInference | null {
  const callUsages = usages.filter((usage) => usage.kind === "function-call");
  if (callUsages.length === 0) {
    return null;
  }

  const signatures = new Set<string>();
  let explicitSignatureCount = 0;

  for (const usage of callUsages) {
    const args = usage.argumentTypes ?? [];
    const sourceNames = usage.argumentNames ?? [];
    let hasSpecificArgument = args.length === 0;
    const usedNames = new Map<string, number>();
    const params = args.map((arg, index) => {
      const normalized = normalizeTypeText(arg.text);
      const baseName = normalizeParameterName(
        sourceNames[index] ?? `arg${index}`,
        index
      );
      const seen = usedNames.get(baseName) ?? 0;
      usedNames.set(baseName, seen + 1);
      const finalName = seen === 0 ? baseName : `${baseName}${seen + 1}`;

      if (isUsefulType(arg.text) && !containsAnyKeyword(normalized)) {
        hasSpecificArgument = true;
        return `${finalName}: ${normalized}`;
      }

      return `${finalName}: unknown`;
    });

    if (!hasSpecificArgument) {
      continue;
    }

    explicitSignatureCount += 1;
    signatures.add(`(${params.join(", ")}) => unknown`);
  }

  if (signatures.size === 0) {
    return null;
  }

  if (signatures.size === 1) {
    const [singleSignature] = [...signatures];
    if (!singleSignature) {
      return null;
    }

    return {
      typeText: singleSignature,
      score: 8 + explicitSignatureCount * 4,
    };
  }

  return {
    typeText: formatUnionTypeParts(
      [...signatures].sort((a, b) => a.localeCompare(b))
    ),
    score: 8 + explicitSignatureCount * 4,
  };
}

function inferBestType(globalEntry: GlobalUsageMetadata): {
  recommendedType: string | null;
  reason: string;
} {
  const scoreByType = new Map<string, number>();
  const scoreByTypeWithoutAny = new Map<string, number>();

  for (const usage of globalEntry.usages) {
    if (!usage.type?.text) {
      continue;
    }

    if (!isUsefulType(usage.type.text)) {
      continue;
    }

    const normalizedType = normalizeTypeText(usage.type.text);
    const nextScore =
      (scoreByType.get(normalizedType) ?? 0) +
      scoreUsageKind(usage.kind) +
      specificityBonus(normalizedType);

    scoreByType.set(normalizedType, nextScore);

    if (!containsAnyKeyword(normalizedType)) {
      scoreByTypeWithoutAny.set(normalizedType, nextScore);
    }
  }

  const functionType = inferFunctionTypeFromCalls(globalEntry.usages);
  if (functionType) {
    const functionTypeText = functionType.typeText;
    const functionScore =
      functionType.score + specificityBonus(functionTypeText);

    scoreByType.set(
      functionTypeText,
      (scoreByType.get(functionTypeText) ?? 0) + functionScore
    );

    if (!containsAnyKeyword(functionTypeText)) {
      scoreByTypeWithoutAny.set(
        functionTypeText,
        (scoreByTypeWithoutAny.get(functionTypeText) ?? 0) + functionScore
      );
    }
  }

  if (scoreByType.size === 0) {
    return {
      recommendedType: null,
      reason: "No non-any usage types were available.",
    };
  }

  const usingNonAnyCandidates = scoreByTypeWithoutAny.size > 0;
  const activeScoreMap = usingNonAnyCandidates
    ? scoreByTypeWithoutAny
    : scoreByType;

  const ranked = [...activeScoreMap.entries()].sort((a, b) => {
    if (a[1] !== b[1]) {
      return b[1] - a[1];
    }

    if (a[0] === "string" || a[0] === "number" || a[0] === "boolean") {
      return -1;
    }
    if (b[0] === "string" || b[0] === "number" || b[0] === "boolean") {
      return 1;
    }

    return a[0].localeCompare(b[0]);
  });

  const best = ranked[0];
  if (!best) {
    return {
      recommendedType: null,
      reason: "No ranked candidates were available.",
    };
  }

  const preferredArgumentNames = getPreferredArgumentNames(globalEntry.usages);
  const [bestType, bestScore] = best;
  const second = ranked[1];

  if (second && second[1] === bestScore && second[0] !== bestType) {
    const unionType = formatUnionTypeParts([bestType, second[0]]);
    return {
      recommendedType: applyPreferredArgumentNames(
        unionType,
        preferredArgumentNames
      ),
      reason: `${usingNonAnyCandidates ? "Preferred non-any evidence. " : ""}Top evidence tied between ${bestType} and ${second[0]}.`,
    };
  }

  const namedBestType = applyPreferredArgumentNames(
    bestType,
    preferredArgumentNames
  );

  return {
    recommendedType: namedBestType,
    reason: `${usingNonAnyCandidates ? "Preferred non-any evidence. " : ""}Selected by strongest usage evidence score (${bestScore}).`,
  };
}

function findDeclarationAtLocation(
  declarations: VariableDeclaration[],
  expectedName: string,
  lineNumber: number
): VariableDeclaration | undefined {
  const exactMatch = declarations.find((declaration) => {
    if (declaration.getName() !== expectedName) {
      return false;
    }

    const line = declaration
      .getSourceFile()
      .getLineAndColumnAtPos(declaration.getNameNode().getStart()).line;

    return line === lineNumber;
  });

  if (exactMatch) {
    return exactMatch;
  }

  const nameMatches = declarations.filter(
    (declaration) => declaration.getName() === expectedName
  );

  if (nameMatches.length === 0) {
    return undefined;
  }

  if (nameMatches.length === 1) {
    return nameMatches[0];
  }

  return nameMatches.sort((a, b) => {
    const aLine = a
      .getSourceFile()
      .getLineAndColumnAtPos(a.getNameNode().getStart()).line;
    const bLine = b
      .getSourceFile()
      .getLineAndColumnAtPos(b.getNameNode().getStart()).line;

    return Math.abs(aLine - lineNumber) - Math.abs(bLine - lineNumber);
  })[0];
}

async function inferGlobalTypesFromUsage() {
  const mapText = await readFile(USAGE_MAP_PATH, "utf8");
  const usageReport = JSON.parse(mapText) as UsageReport;

  const project = new Project({
    tsConfigFilePath: path.resolve("tsconfig.json"),
  });

  const recommendations: Recommendation[] = [];
  let updatedDeclarations = 0;
  let skippedDeclarations = 0;

  for (const globalEntry of usageReport.globals) {
    const inference = inferBestType(globalEntry);
    if (!inference.recommendedType) {
      skippedDeclarations += 1;
      continue;
    }

    const definitionPath = resolveWorkspacePath(
      globalEntry.definitionLocation.filePath
    );
    const sourceFile = project.getSourceFile(definitionPath);

    if (!sourceFile) {
      skippedDeclarations += 1;
      continue;
    }

    const declarations = sourceFile.getDescendantsOfKind(
      SyntaxKind.VariableDeclaration
    );
    const declaration = findDeclarationAtLocation(
      declarations,
      globalEntry.name,
      globalEntry.definitionLocation.lineNumber
    );

    if (!declaration) {
      skippedDeclarations += 1;
      continue;
    }

    const currentType =
      declaration.getTypeNode()?.getText()?.trim() ??
      declaration.getType().getText();
    if (currentType === inference.recommendedType) {
      skippedDeclarations += 1;
      continue;
    }

    declaration.setType(inference.recommendedType);
    updatedDeclarations += 1;

    recommendations.push({
      name: globalEntry.name,
      definitionLocation: globalEntry.definitionLocation,
      currentType,
      recommendedType: inference.recommendedType,
      reason: inference.reason,
    });
  }

  await project.save();

  const report: RecommendationReport = {
    generatedAt: new Date().toISOString(),
    inputMapPath: path
      .relative(process.cwd(), USAGE_MAP_PATH)
      .replace(/\\/g, "/"),
    updatedDeclarations,
    skippedDeclarations,
    recommendations: recommendations.sort((a, b) =>
      a.name.localeCompare(b.name)
    ),
  };

  await writeFile(
    RECOMMENDATION_REPORT_PATH,
    `${JSON.stringify(report, null, 2)}\n`,
    "utf8"
  );

  console.log(
    `Updated ${updatedDeclarations} global declarations and wrote ${path
      .relative(process.cwd(), RECOMMENDATION_REPORT_PATH)
      .replace(/\\/g, "/")}.`
  );
}

await inferGlobalTypesFromUsage();
