import { writeFile } from "node:fs/promises";
import path from "node:path";
import {
  Node,
  Project,
  SyntaxKind,
  Type,
  TypeFormatFlags,
  VariableDeclaration,
} from "ts-morph";

type LocationMetadata = {
  filePath: string;
  lineNumber: number;
  columnNumber: number;
};

type TypeMetadata = {
  text: string;
  name: string;
  genericTypeParameters?: string[];
};

type UsageMetadata = {
  location: LocationMetadata;
  kind: string;
  type?: TypeMetadata;
  argumentTypes?: TypeMetadata[];
  argumentNames?: string[];
  propertyName?: string;
  loopRole?: string;
};

type GlobalUsageMetadata = {
  definitionLocation: LocationMetadata;
  name: string;
  usages: UsageMetadata[];
};

type UsageReport = {
  generatedAt: string;
  outputVersion: string;
  sourceFiles: string[];
  globals: GlobalUsageMetadata[];
};

type GlobalDeclaration = {
  name: string;
  version: number;
  declaration: VariableDeclaration;
};

const OUTPUT_PATH = path.resolve(
  "typings",
  "autogenerated_globals_any_usage_map.json"
);

function toRelativePath(filePath: string): string {
  return path.relative(process.cwd(), filePath).replace(/\\/g, "/");
}

function getLocation(node: Node): LocationMetadata {
  const sourceFile = node.getSourceFile();
  const lineAndColumn = sourceFile.getLineAndColumnAtPos(node.getStart());

  return {
    filePath: toRelativePath(sourceFile.getFilePath()),
    lineNumber: lineAndColumn.line,
    columnNumber: lineAndColumn.column,
  };
}

function splitGenericParameters(text: string): string[] {
  const result: string[] = [];
  let depth = 0;
  let current = "";

  for (const char of text) {
    if (char === "<") {
      depth += 1;
      current += char;
      continue;
    }

    if (char === ">") {
      depth -= 1;
      current += char;
      continue;
    }

    if (char === "," && depth === 0) {
      if (current.trim()) {
        result.push(current.trim());
      }
      current = "";
      continue;
    }

    current += char;
  }

  if (current.trim()) {
    result.push(current.trim());
  }

  return result;
}

function describeType(type: Type | undefined): TypeMetadata | undefined {
  if (!type) {
    return undefined;
  }

  const text = type.getText(undefined, TypeFormatFlags.NoTruncation);
  if (!text) {
    return undefined;
  }

  const genericMatch = text.match(/^([A-Za-z_$][\w$.]*)<(.*)>$/);
  if (!genericMatch) {
    return {
      text,
      name: text,
    };
  }

  const genericTypeParameters = splitGenericParameters(genericMatch[2] ?? "");

  return {
    text,
    name: genericMatch[1] ?? text,
    genericTypeParameters,
  };
}

function determineForStatementRole(
  forStatement: Node,
  node: Node
): string | undefined {
  if (!Node.isForStatement(forStatement)) {
    return undefined;
  }

  const initializer = forStatement.getInitializer();
  if (
    initializer &&
    (initializer === node || initializer.getDescendants().includes(node))
  ) {
    return "initializer";
  }

  const condition = forStatement.getCondition();
  if (
    condition &&
    (condition === node || condition.getDescendants().includes(node))
  ) {
    return "condition";
  }

  const incrementor = forStatement.getIncrementor();
  if (
    incrementor &&
    (incrementor === node || incrementor.getDescendants().includes(node))
  ) {
    return "incrementor";
  }

  return "body";
}

function isAssignmentOperator(kind: SyntaxKind): boolean {
  return (
    kind === SyntaxKind.EqualsToken ||
    kind === SyntaxKind.PlusEqualsToken ||
    kind === SyntaxKind.MinusEqualsToken ||
    kind === SyntaxKind.AsteriskEqualsToken ||
    kind === SyntaxKind.AsteriskAsteriskEqualsToken ||
    kind === SyntaxKind.SlashEqualsToken ||
    kind === SyntaxKind.PercentEqualsToken ||
    kind === SyntaxKind.AmpersandEqualsToken ||
    kind === SyntaxKind.BarEqualsToken ||
    kind === SyntaxKind.CaretEqualsToken ||
    kind === SyntaxKind.LessThanLessThanEqualsToken ||
    kind === SyntaxKind.GreaterThanGreaterThanEqualsToken ||
    kind === SyntaxKind.GreaterThanGreaterThanGreaterThanEqualsToken ||
    kind === SyntaxKind.BarBarEqualsToken ||
    kind === SyntaxKind.AmpersandAmpersandEqualsToken ||
    kind === SyntaxKind.QuestionQuestionEqualsToken
  );
}

function normalizeIdentifierName(text: string, fallbackIndex: number): string {
  const cleaned = text
    .trim()
    .replace(/^[^A-Za-z_$]+/, "")
    .replace(/[^\w$]/g, "_")
    .replace(/_+/g, "_");

  if (!cleaned || !/^[A-Za-z_$][\w$]*$/.test(cleaned)) {
    return `arg${fallbackIndex}`;
  }

  return cleaned;
}

function inferArgumentName(argument: Node, index: number): string {
  if (Node.isIdentifier(argument)) {
    return normalizeIdentifierName(argument.getText(), index);
  }

  if (Node.isPropertyAccessExpression(argument)) {
    return normalizeIdentifierName(argument.getName(), index);
  }

  if (Node.isElementAccessExpression(argument)) {
    const argExpression = argument.getArgumentExpression();
    if (
      argExpression &&
      (Node.isStringLiteral(argExpression) ||
        Node.isNoSubstitutionTemplateLiteral(argExpression))
    ) {
      return normalizeIdentifierName(argExpression.getLiteralText(), index);
    }

    return normalizeIdentifierName(argument.getExpression().getText(), index);
  }

  if (Node.isObjectLiteralExpression(argument)) {
    return "options";
  }

  if (Node.isArrayLiteralExpression(argument)) {
    return "items";
  }

  if (
    Node.isStringLiteral(argument) ||
    Node.isNoSubstitutionTemplateLiteral(argument)
  ) {
    return "text";
  }

  if (Node.isNumericLiteral(argument)) {
    return "value";
  }

  if (
    argument.getKind() === SyntaxKind.TrueKeyword ||
    argument.getKind() === SyntaxKind.FalseKeyword
  ) {
    return "flag";
  }

  return `arg${index}`;
}

function getCallArgumentNames(callExpression: Node): string[] {
  if (!Node.isCallExpression(callExpression)) {
    return [];
  }

  const raw = callExpression
    .getArguments()
    .map((argument, index) => inferArgumentName(argument, index));

  const counts = new Map<string, number>();
  return raw.map((name, index) => {
    const base = normalizeIdentifierName(name, index);
    const seen = counts.get(base) ?? 0;
    counts.set(base, seen + 1);

    if (seen === 0) {
      return base;
    }

    return `${base}${seen + 1}`;
  });
}

function classifyUsage(referenceNode: Node): UsageMetadata {
  const location = getLocation(referenceNode);
  const parent = referenceNode.getParent();

  if (!parent) {
    return {
      location,
      kind: "identifier-read",
      type: describeType(referenceNode.getType()),
    };
  }

  if (
    Node.isPropertyAccessExpression(parent) &&
    parent.getNameNode() === referenceNode
  ) {
    const grandParent = parent.getParent();

    if (
      grandParent &&
      Node.isBinaryExpression(grandParent) &&
      grandParent.getLeft() === parent &&
      isAssignmentOperator(grandParent.getOperatorToken().getKind())
    ) {
      return {
        location,
        kind: "assignment",
        propertyName: parent.getName(),
        type: describeType(grandParent.getRight().getType()),
      };
    }

    if (
      grandParent &&
      Node.isCallExpression(grandParent) &&
      grandParent.getExpression() === parent
    ) {
      const argumentTypes = grandParent
        .getArguments()
        .map((arg) => describeType(arg.getType()))
        .filter(Boolean) as TypeMetadata[];

      return {
        location,
        kind: "function-call",
        propertyName: parent.getName(),
        argumentTypes,
        argumentNames: getCallArgumentNames(grandParent),
        type: describeType(parent.getType()),
      };
    }

    if (
      grandParent &&
      Node.isVariableDeclaration(grandParent) &&
      grandParent.getInitializer() === parent
    ) {
      return {
        location,
        kind: "variable-initializer",
        propertyName: parent.getName(),
        type: describeType(grandParent.getType()),
      };
    }

    return {
      location,
      kind: "property-access",
      propertyName: parent.getName(),
      type: describeType(parent.getType()),
    };
  }

  if (Node.isBinaryExpression(parent)) {
    const isAssignment = isAssignmentOperator(
      parent.getOperatorToken().getKind()
    );

    if (isAssignment && parent.getLeft() === referenceNode) {
      return {
        location,
        kind: "assignment",
        type: describeType(parent.getRight().getType()),
      };
    }

    if (isAssignment && parent.getRight() === referenceNode) {
      return {
        location,
        kind: "assignment-rhs",
        type: describeType(referenceNode.getType()),
      };
    }
  }

  if (
    Node.isVariableDeclaration(parent) &&
    parent.getInitializer() === referenceNode
  ) {
    return {
      location,
      kind: "variable-initializer",
      type: describeType(parent.getType()),
    };
  }

  if (Node.isCallExpression(parent)) {
    if (parent.getExpression() === referenceNode) {
      const argumentTypes = parent
        .getArguments()
        .map((arg) => describeType(arg.getType()))
        .filter(Boolean) as TypeMetadata[];

      return {
        location,
        kind: "function-call",
        argumentTypes,
        argumentNames: getCallArgumentNames(parent),
        type: describeType(referenceNode.getType()),
      };
    }

    const argumentIndex = parent
      .getArguments()
      .findIndex((arg) => arg === referenceNode);
    if (argumentIndex >= 0) {
      return {
        location,
        kind: "function-argument",
        type: describeType(referenceNode.getType()),
      };
    }
  }

  if (
    Node.isPropertyAccessExpression(parent) &&
    parent.getExpression() === referenceNode
  ) {
    const grandParent = parent.getParent();

    if (
      grandParent &&
      Node.isCallExpression(grandParent) &&
      grandParent.getExpression() === parent
    ) {
      return {
        location,
        kind: "method-call",
        propertyName: parent.getName(),
        argumentTypes: grandParent
          .getArguments()
          .map((arg) => describeType(arg.getType()))
          .filter(Boolean) as TypeMetadata[],
      };
    }

    return {
      location,
      kind: "property-access",
      propertyName: parent.getName(),
      type: describeType(parent.getType()),
    };
  }

  if (
    Node.isElementAccessExpression(parent) &&
    parent.getExpression() === referenceNode
  ) {
    return {
      location,
      kind: "element-access",
      type: describeType(parent.getType()),
    };
  }

  if (Node.isForStatement(parent)) {
    return {
      location,
      kind: "for-loop",
      loopRole: determineForStatementRole(parent, referenceNode),
      type: describeType(referenceNode.getType()),
    };
  }

  if (
    Node.isForOfStatement(parent) &&
    parent.getExpression() === referenceNode
  ) {
    return {
      location,
      kind: "for-of-loop",
      loopRole: "expression",
      type: describeType(referenceNode.getType()),
    };
  }

  if (
    Node.isForInStatement(parent) &&
    parent.getExpression() === referenceNode
  ) {
    return {
      location,
      kind: "for-in-loop",
      loopRole: "expression",
      type: describeType(referenceNode.getType()),
    };
  }

  if (Node.isIfStatement(parent) && parent.getExpression() === referenceNode) {
    return {
      location,
      kind: "if-condition",
      type: describeType(referenceNode.getType()),
    };
  }

  if (
    Node.isPrefixUnaryExpression(parent) ||
    Node.isPostfixUnaryExpression(parent) ||
    parent.getKind() === SyntaxKind.DeleteExpression
  ) {
    return {
      location,
      kind: "unary-operation",
      type: describeType(referenceNode.getType()),
    };
  }

  return {
    location,
    kind: "identifier-read",
    type: describeType(referenceNode.getType()),
  };
}

function getDeclarationVersion(filePath: string): number {
  const baseName = path.basename(filePath);

  const numberedMatch = baseName.match(/^autogenerated_globals_(\d+)\.d\.ts$/);
  if (numberedMatch) {
    const numberValue = Number(numberedMatch[1]);
    if (!Number.isNaN(numberValue)) {
      return numberValue;
    }
  }

  if (baseName === "autogenerated_globals.d.ts") {
    return 0;
  }

  return -1;
}

function collectAnyGlobalDeclarations(project: Project): GlobalDeclaration[] {
  const candidates = project.getSourceFiles().filter((sourceFile) => {
    const relativePath = toRelativePath(sourceFile.getFilePath());
    return /^typings\/autogenerated_globals(?:_\d+)?\.d\.ts$/.test(
      relativePath
    );
  });
  const declarationsByName = new Map<string, GlobalDeclaration>();

  for (const sourceFile of candidates) {
    const version = getDeclarationVersion(sourceFile.getFilePath());

    for (const declaration of sourceFile.getDescendantsOfKind(
      SyntaxKind.VariableDeclaration
    )) {
      const explicitTypeText = declaration.getTypeNode()?.getText()?.trim();
      const isAnyType =
        explicitTypeText === "any" || declaration.getType().isAny();
      if (!isAnyType) {
        continue;
      }

      const name = declaration.getName();
      const existing = declarationsByName.get(name);
      if (!existing || version > existing.version) {
        declarationsByName.set(name, {
          name,
          version,
          declaration,
        });
      }
    }
  }

  return [...declarationsByName.values()].sort((a, b) =>
    a.name.localeCompare(b.name)
  );
}

function createUsageMetadata(entry: GlobalDeclaration): GlobalUsageMetadata {
  const declarationNameNode = entry.declaration.getNameNode();
  const references = entry.declaration.findReferences();
  const usages: UsageMetadata[] = [];
  const seen = new Set<string>();

  for (const reference of references) {
    for (const referenceEntry of reference.getReferences()) {
      if (referenceEntry.isDefinition()) {
        continue;
      }

      const node = referenceEntry.getNode();
      if (node.getSourceFile().isDeclarationFile()) {
        continue;
      }

      const usage = classifyUsage(node);
      const key = `${usage.location.filePath}:${usage.location.lineNumber}:${usage.location.columnNumber}:${usage.kind}`;

      if (!seen.has(key)) {
        seen.add(key);
        usages.push(usage);
      }
    }
  }

  usages.sort((a, b) => {
    if (a.location.filePath !== b.location.filePath) {
      return a.location.filePath.localeCompare(b.location.filePath);
    }
    if (a.location.lineNumber !== b.location.lineNumber) {
      return a.location.lineNumber - b.location.lineNumber;
    }
    return a.location.columnNumber - b.location.columnNumber;
  });

  return {
    definitionLocation: getLocation(declarationNameNode),
    name: entry.name,
    usages,
  };
}

async function mapAnyUsage() {
  const project = new Project({
    tsConfigFilePath: path.resolve("tsconfig.json"),
    skipAddingFilesFromTsConfig: false,
  });

  const anyGlobalDeclarations = collectAnyGlobalDeclarations(project);
  const globals = anyGlobalDeclarations.map((entry) =>
    createUsageMetadata(entry)
  );

  const sourceFiles = [
    ...new Set(
      anyGlobalDeclarations.map((entry) =>
        toRelativePath(entry.declaration.getSourceFile().getFilePath())
      )
    ),
  ].sort((a, b) => a.localeCompare(b));

  const output: UsageReport = {
    generatedAt: new Date().toISOString(),
    outputVersion: "1",
    sourceFiles,
    globals,
  };

  await writeFile(OUTPUT_PATH, `${JSON.stringify(output, null, 2)}\n`, "utf8");

  console.log(
    `Mapped ${globals.length} any-typed globals and wrote ${toRelativePath(OUTPUT_PATH)}.`
  );
}

await mapAnyUsage();
