import { readdir } from "node:fs/promises";
import path from "node:path";
import { Node, Project, SourceFile, SyntaxKind } from "ts-morph";

type RefactorStats = {
  filesScanned: number;
  filesUpdated: number;
  replacedGlobalThisAccesses: number;
  replacedBareGlobals: number;
  insertedHooks: number;
  addedImports: number;
  detectedGlobals: number;
};

const TYPINGS_DIR = path.resolve("typings");
const GLOBALS_IMPORT_MODULE = "app.hooks.globalsContext";
const GLOBALS_HOOK_NAME = "useGlobalsContext";
const TARGET_COMPONENT_GLOB = [
  "packages/**/app/components/**/*.tsx",
  "packages/**/app/components/**/*.jsx",
];

function isDryRunEnabled(): boolean {
  return process.argv.slice(2).includes("--dry-run");
}

function toRelative(filePath: string): string {
  return path.relative(process.cwd(), filePath).replace(/\\/g, "/");
}

async function getAutogeneratedGlobalDtsPaths(): Promise<string[]> {
  const files = await readdir(TYPINGS_DIR, { withFileTypes: true });
  const result: string[] = [];

  for (const entry of files) {
    if (!entry.isFile()) {
      continue;
    }

    if (/^autogenerated_globals(?:_[^.]+)?\.d\.ts$/.test(entry.name)) {
      result.push(path.resolve(TYPINGS_DIR, entry.name));
    }
  }

  return result.sort((a, b) => a.localeCompare(b));
}

function collectGlobalNames(project: Project, dtsPaths: string[]): Set<string> {
  for (const dtsPath of dtsPaths) {
    project.addSourceFileAtPathIfExists(dtsPath);
  }

  const names = new Set<string>();
  const declarationFiles = project
    .getSourceFiles()
    .filter((sourceFile) => dtsPaths.includes(sourceFile.getFilePath()));

  for (const sourceFile of declarationFiles) {
    for (const declaration of sourceFile.getDescendantsOfKind(
      SyntaxKind.VariableDeclaration
    )) {
      const nameNode = declaration.getNameNode();
      if (Node.isIdentifier(nameNode)) {
        names.add(nameNode.getText());
      }
    }
  }

  return names;
}

function isInsideTypePosition(identifier: Node): boolean {
  return identifier
    .getAncestors()
    .some((ancestor) => Node.isTypeNode(ancestor));
}

function isIdentifierUsageCandidate(identifier: Node): boolean {
  const parent = identifier.getParent();
  if (!parent) {
    return false;
  }

  if (
    Node.isImportSpecifier(parent) ||
    Node.isImportClause(parent) ||
    Node.isImportDeclaration(parent) ||
    Node.isExportSpecifier(parent) ||
    Node.isTypeAliasDeclaration(parent) ||
    Node.isInterfaceDeclaration(parent) ||
    Node.isPropertySignature(parent) ||
    Node.isTypeReference(parent)
  ) {
    return false;
  }

  if (
    (Node.isVariableDeclaration(parent) ||
      Node.isFunctionDeclaration(parent) ||
      Node.isParameterDeclaration(parent) ||
      Node.isClassDeclaration(parent) ||
      Node.isEnumDeclaration(parent) ||
      Node.isPropertyDeclaration(parent) ||
      Node.isBindingElement(parent)) &&
    parent.getNameNode() === identifier
  ) {
    return false;
  }

  if (
    Node.isPropertyAccessExpression(parent) &&
    parent.getNameNode() === identifier
  ) {
    return false;
  }

  if (
    Node.isPropertyAssignment(parent) &&
    parent.getNameNode() === identifier
  ) {
    return false;
  }

  if (
    Node.isShorthandPropertyAssignment(parent) &&
    parent.getNameNode() === identifier
  ) {
    return true;
  }

  return !isInsideTypePosition(identifier);
}

function isAutogeneratedGlobalsDeclarationPath(filePath: string): boolean {
  const normalized = filePath.replace(/\\/g, "/");
  return /\/typings\/autogenerated_globals(?:_[^.]+)?\.d\.ts$/.test(normalized);
}

function findOwningComponent(node: Node): Node | null {
  let current = node.getParent();

  while (current) {
    if (
      Node.isFunctionDeclaration(current) ||
      Node.isFunctionExpression(current) ||
      Node.isArrowFunction(current) ||
      Node.isMethodDeclaration(current)
    ) {
      const body = current.getBody();
      if (!body) {
        current = current.getParent();
        continue;
      }

      const hasJsx =
        body.getDescendantsOfKind(SyntaxKind.JsxElement).length > 0 ||
        body.getDescendantsOfKind(SyntaxKind.JsxSelfClosingElement).length >
          0 ||
        body.getDescendantsOfKind(SyntaxKind.JsxFragment).length > 0;

      if (hasJsx) {
        return current;
      }
    }

    current = current.getParent();
  }

  return null;
}

function ensureGlobalsImport(sourceFile: SourceFile): boolean {
  const imports = sourceFile.getImportDeclarations();
  for (const declaration of imports) {
    if (declaration.getModuleSpecifierValue() !== GLOBALS_IMPORT_MODULE) {
      continue;
    }

    const named = declaration.getNamedImports();
    if (named.some((specifier) => specifier.getName() === GLOBALS_HOOK_NAME)) {
      return false;
    }

    declaration.addNamedImport(GLOBALS_HOOK_NAME);
    return true;
  }

  sourceFile.addImportDeclaration({
    moduleSpecifier: GLOBALS_IMPORT_MODULE,
    namedImports: [GLOBALS_HOOK_NAME],
  });
  return true;
}

function hasTopLevelGlobalsBinding(component: Node): boolean {
  if (
    !Node.isFunctionDeclaration(component) &&
    !Node.isFunctionExpression(component) &&
    !Node.isArrowFunction(component) &&
    !Node.isMethodDeclaration(component)
  ) {
    return false;
  }

  const body = component.getBody();
  if (!body || !Node.isBlock(body)) {
    return false;
  }

  for (const statement of body.getStatements()) {
    if (!Node.isVariableStatement(statement)) {
      continue;
    }

    for (const declaration of statement.getDeclarations()) {
      if (declaration.getName() === "globals") {
        return true;
      }
    }
  }

  return false;
}

function ensureGlobalsHookInComponent(component: Node): boolean {
  if (
    !Node.isFunctionDeclaration(component) &&
    !Node.isFunctionExpression(component) &&
    !Node.isArrowFunction(component) &&
    !Node.isMethodDeclaration(component)
  ) {
    return false;
  }

  const body = component.getBody();
  if (!body || !Node.isBlock(body)) {
    return false;
  }

  if (hasTopLevelGlobalsBinding(component)) {
    return false;
  }

  body.insertStatements(0, "const globals = useGlobalsContext();");
  return true;
}

function refactorSourceFile(
  sourceFile: SourceFile,
  globalsSet: Set<string>,
  stats: RefactorStats
): boolean {
  let fileChanged = false;
  const componentsNeedingHook = new Set<Node>();

  const propertyAccesses = sourceFile.getDescendantsOfKind(
    SyntaxKind.PropertyAccessExpression
  );
  for (const propertyAccess of propertyAccesses) {
    const expression = propertyAccess.getExpression();
    const name = propertyAccess.getName();
    if (expression.getText() !== "globalThis" || !globalsSet.has(name)) {
      continue;
    }

    const owningComponent = findOwningComponent(propertyAccess);
    if (!owningComponent) {
      continue;
    }

    propertyAccess.replaceWithText(`globals.${name}`);
    componentsNeedingHook.add(owningComponent);
    stats.replacedGlobalThisAccesses += 1;
    fileChanged = true;
  }

  const elementAccesses = sourceFile.getDescendantsOfKind(
    SyntaxKind.ElementAccessExpression
  );
  for (const elementAccess of elementAccesses) {
    const expression = elementAccess.getExpression();
    if (expression.getText() !== "globalThis") {
      continue;
    }

    const argumentExpression = elementAccess.getArgumentExpression();
    if (!argumentExpression) {
      continue;
    }

    if (
      !Node.isStringLiteral(argumentExpression) &&
      !Node.isNoSubstitutionTemplateLiteral(argumentExpression)
    ) {
      continue;
    }

    const name = argumentExpression.getLiteralText();
    if (!globalsSet.has(name)) {
      continue;
    }

    const owningComponent = findOwningComponent(elementAccess);
    if (!owningComponent) {
      continue;
    }

    elementAccess.replaceWithText(`globals.${name}`);
    componentsNeedingHook.add(owningComponent);
    stats.replacedGlobalThisAccesses += 1;
    fileChanged = true;
  }

  const identifiers = sourceFile.getDescendantsOfKind(SyntaxKind.Identifier);
  for (const identifier of identifiers) {
    const name = identifier.getText();
    if (!globalsSet.has(name) || !isIdentifierUsageCandidate(identifier)) {
      continue;
    }

    const symbol = identifier.getSymbol();
    if (!symbol) {
      continue;
    }

    const declarations = symbol.getDeclarations();
    if (declarations.length === 0) {
      continue;
    }

    const allAutogeneratedGlobals = declarations.every((declaration) =>
      isAutogeneratedGlobalsDeclarationPath(
        declaration.getSourceFile().getFilePath()
      )
    );
    if (!allAutogeneratedGlobals) {
      continue;
    }

    const owningComponent = findOwningComponent(identifier);
    if (!owningComponent) {
      continue;
    }

    if (Node.isShorthandPropertyAssignment(identifier.getParent())) {
      identifier
        .getParentIfKind(SyntaxKind.ShorthandPropertyAssignment)
        ?.replaceWithText(`${name}: globals.${name}`);
    } else {
      identifier.replaceWithText(`globals.${name}`);
    }

    componentsNeedingHook.add(owningComponent);
    stats.replacedBareGlobals += 1;
    fileChanged = true;
  }

  if (componentsNeedingHook.size > 0) {
    if (ensureGlobalsImport(sourceFile)) {
      stats.addedImports += 1;
      fileChanged = true;
    }

    for (const component of componentsNeedingHook) {
      if (ensureGlobalsHookInComponent(component)) {
        stats.insertedHooks += 1;
        fileChanged = true;
      }
    }
  }

  return fileChanged;
}

async function run() {
  const dryRun = isDryRunEnabled();
  const project = new Project({
    tsConfigFilePath: path.resolve("tsconfig.json"),
  });

  const dtsPaths = await getAutogeneratedGlobalDtsPaths();
  if (dtsPaths.length === 0) {
    console.log("No autogenerated globals declaration files were found.");
    return;
  }

  const globalsSet = collectGlobalNames(project, dtsPaths);
  if (globalsSet.size === 0) {
    console.log("No globals were discovered from autogenerated declarations.");
    return;
  }

  const componentFiles: SourceFile[] = [];
  for (const pattern of TARGET_COMPONENT_GLOB) {
    componentFiles.push(...project.getSourceFiles(pattern));
  }

  const stats: RefactorStats = {
    filesScanned: componentFiles.length,
    filesUpdated: 0,
    replacedGlobalThisAccesses: 0,
    replacedBareGlobals: 0,
    insertedHooks: 0,
    addedImports: 0,
    detectedGlobals: globalsSet.size,
  };

  const updatedFiles: string[] = [];
  for (const sourceFile of componentFiles) {
    const changed = refactorSourceFile(sourceFile, globalsSet, stats);
    if (changed) {
      stats.filesUpdated += 1;
      updatedFiles.push(toRelative(sourceFile.getFilePath()));
    }
  }

  if (!dryRun) {
    await project.save();
  }

  console.log(
    dryRun
      ? "Global context refactor dry run complete."
      : "Global context refactor complete."
  );
  console.log(JSON.stringify(stats, null, 2));
  if (updatedFiles.length > 0) {
    console.log("Updated files:");
    for (const file of updatedFiles) {
      console.log(`- ${file}`);
    }
  }
}

await run();
