import type { Signal } from "@preact/signals";

export interface CustomAnnotationTextEditorManager {
  instanceId: Signal<string>;
  className: Signal<string | undefined>;
  style: Signal<Record<string, any> | undefined>;
  minHeight: Signal<number>;
  showMoreOptions: Signal<boolean>;
  headingControls: Signal<boolean>;
  editorId: Signal<string>;
  showPreview: Signal<boolean>;
  loading: Signal<boolean>;
  recording: Signal<string | null>;
  name: Signal<string>;
  link: Signal<string>;
  commandBoxFilter: Signal<string>;
  isCommandBox: Signal<boolean>;
  isTagSuggestionsOpen: Signal<boolean>;
  isPlaylistSuggestionOpen: Signal<boolean>;
  loadingPlaylistOptions: Signal<boolean>;
  savingPlaylist: Signal<boolean>;
  textColor: Signal<string>;
  bgColor: Signal<string>;
  fontPx: Signal<number>;
  lineSpacing: Signal<number>;
  padY: Signal<number>;
  padX: Signal<number>;
  priority: Signal<string[]>;
  visibleIds: Signal<string[]>;
  overflowIds: Signal<string[]>;
  showOverflow: Signal<boolean>;
  showTuning: Signal<boolean>;
  draftOrder: Signal<string[]>;
  data: Signal<any>;
  dragState: Signal<{ isDragOver: boolean }>;
  tagOptions: Signal<{ key: string; label: string }[]>;
  playlistOptions: Signal<{ key: string; label: string; metaData: any }[]>;
  isMic: Signal<boolean>;
  isVideo: Signal<boolean>;
  isLink: Signal<boolean>;
  filteredCommandBoxOptions: Signal<
    { icon: string; label: string; onClick: () => void }[]
  >;
  syncProps: (
    props: import("ext_discover.interfaces.components.CustomAnnotationTextEditor").CustomAnnotationTextEditorProps
  ) => void;
  mount: () => void;
  unmount: () => void;
  setEditorRef: (el: HTMLElement | null) => void;
  setToolbarRef: (el: HTMLElement | null) => void;
  setMeasurerRef: (el: HTMLElement | null) => void;
  setItemRef: (id: string, el: HTMLElement | null) => void;
  setDragRootRef: (el: HTMLElement | null) => void;
  setFileImgInputRef: (el: HTMLInputElement | null) => void;
  setFileJsonInputRef: (el: HTMLInputElement | null) => void;
  getInstanceKey: () => string;
  onClickTags: (tag: any) => void;
  onClickPlaylist: (playlist: any) => Promise<void>;
  toggleTagSuggestions: () => void;
  togglePlaylistSuggestions: () => void;
  toggleCommandBox: () => void;
  togglePreview: () => void;
  handleDropFiles: (files: any) => Promise<void>;
  onSaveAndAdd: () => Promise<void>;
  onImageSelected: (e: any) => void;
  onJSONSelected: (e: any) => void;
  onAddLink: () => void;
  moveDraft: (i: number, dir: number) => void;
  saveDraft: () => void;
  orderedIds: () => string[];
  chain: (method: string) => void;
  chainWith: (method: string) => void;
  chainArg: (method: string, arg: any) => void;
  onPickImage: () => void;
  onPickJSON: () => void;
  computeLayout: () => void;
  setTextColor: (value: string) => void;
  setBgColor: (value: string) => void;
  setFontPx: (value: number) => void;
  setLineSpacing: (value: number) => void;
  setPadY: (value: number) => void;
  setPadX: (value: number) => void;
  setName: (value: string) => void;
  setLink: (value: string) => void;
  setData: (value: any) => void;
  setRecording: (value: string | null) => void;
  setLoading: (value: boolean) => void;
  setIsTagSuggestionsOpen: (value: boolean) => void;
  setIsPlaylistSuggestionOpen: (value: boolean) => void;
  setShowOverflow: (value: boolean | ((prev: boolean) => boolean)) => void;
  setShowTuning: (value: boolean) => void;
  setDraftOrder: (value: string[] | ((prev: string[]) => string[])) => void;
  Cmds: Record<string, any>;
}
